hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "40c4e7301977a6ca2e32fbfedd899572cf69fc72565b1494c4cb5c7b17809a4c"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "6334807483214e21b0457dc485699a5b6ceadaa3d96500954d1b7704f874083e"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "1f1d9fb411af408ac6ae2406e0f50c69ce80a5957c2d0c063416e394fda7d3a2"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "c06bfaed1bb50e273d42e7238ba2e14684080d898028e2cd49d89b3272494c41"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "81f33c0b5ee9c16ef3bbf97e0f8caed6eb3add0555c41dae7ee926c734ae8c7d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "c203d45ab48ce4b7b5e19a2a4e7c3b3748d8dfcd4d09d97fb3ffe59892e44a14"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "f3b55f8524a5944355b627217c37eaa6de342c8f5fc9c4b7df860e79e54f0767"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "9abd1cefdb8c043482e57770bf9451c6e2e58d87711aeefcccbea060ac9d12ad"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "7bc091eb750fe27046de8c9a14671cbf0afa9f77675022e5dba499da786434df"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "b2db6f14261ef05bd3da91bb176439cc019b33a9d5ee9879f3b089973fb62e35"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "51d20b511a9baad51e77259af530f0ab36ea50b69cc47691fb7f99c0b114e634"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "2ef8ffdba4eb43f09d12f08e33cddd14e2a882ef35f04a805633ea33265ada2c"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "29ab91e23d3b9045c0074fd3d15ae625ab054de8a911cd2f814a04fcc8b18f63"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "8cd1809a40c44d596a509bd88db8ed3edc572977a400876531233f6ec4bb5c94"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "8c42708d1a5b99b6080d7919c072bbbc6d1254558d61bfb15397f1013a626f0a"
metafile = true

[[files]]
file = "mods/pistorder.pw.toml"
hash = "52339d35b3bafc58175540069b2dd66b563fdd2b707dc6bbaf935e7ed0224438"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "0f1c0f343cc00f8025912bdad7b4efa50f7a05bc87f43a6f871e6d066c8656ce"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "2751f21ea7a3d260b7558c01b5c4cd2d1f01c7a2ab703207b945b185013e3636"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "ff97c0826a786ef9d993b6a93e0b6bdaf734bc193eb19504d2ef60e089382174"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "49e67d8a8cbae979b97071253955fe75b8cb3db789ca40a4140548790e2fd3a3"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "7b5f96554cd02083d5eff7400cf429b5164a95c405fc2db2aa2f27d48921f68e"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
