hash-format = "sha256"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "710e9bb02a1a6d972628c4d5c1fe3bfac5a54bc31976ff7c9f06665b8d8cbae6"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "51cc9f61e61a0b5f8baea5f2a8ddb62a12eddfa66110b622649f0f114b24b56e"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "7a49bd7ce2fc30617b19d139700b8003e336f77334ac46ed00e9decb89188670"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "c375509df57d1f34316b22e90ea0d233dc744d4e453b938d592d835e1463d8e4"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "992f3cc0b18ddf673a133b5c22b9125545be9c97da5060b332a850e3cf417ad0"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "9c1226a35c48dd709baa5455a59930a0fc53307809e210ec9e538df58e567f2a"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "ad4386d8fb46e74ed598e0b8caf32b12bd9779b5dd2298f5c8809f39cc809a88"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "058e98424db0ae665e0938cdf71f39492db639170526096dd04e22d0f598db13"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "c43c7c81fdc38a31e72558301e7e738aec0ad684a9878f05debfcd61207e0116"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "91459e05c6de808c4b5ee9df9d8af0a0f2931ff97876c43b0ee221e38384a5eb"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
hash = "0eef473e8498e5967b2f5fc6caa7a0f6ecea24c8df3f366ab269040b62afac82"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "4f8fa60ab63aac6fba7b2e7bcc10bcc1dda2e0c1ccd1afbec4c80500b952efb3"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "1a4132969d5c89d31e541cafeb75b0dfd49269e73a69175e81090317d0fb58d2"
metafile = true

[[files]]
file = "mods/chest-tracker.pw.toml"
hash = "d496998599ebca053f2413f8adf82384bfc7e5f7ca54d08fd2e1d46bedfca59a"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "b87fccb2cd7144d3dd62c65126ff6d7b86c70b39d97c391ba72bfe5f6391fe47"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "68d9c6e0943edf3cdb03a487c9791beaccc75f70cf2e942175f119303caa73a7"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "f8af8567954b617da27d2efcd343137ad208a404aa9828348cc648a999a1ee2a"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "9a1fa7b3dbb96a9ca27bda4da0b1326b9771269b321c6b3dafbaf8b175727613"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "6064898f8c54b871cdc71c165ae7a5859c758c7bffa03cae2fcb4402ee77b660"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "5edc4507e1662cdc4a0a2e5c87a39a11b498f43f01df1bea2df3330ee9135f64"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "0f79537b5ac37b742f0295bb61aa16b1a7772ba85028a32aba2eca1be44d6bd4"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "c79168539da8ea30e83e7a60f127140bb1288d8436d6ad498f677f2bd27ceaa1"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "be164ffcca6fddbee69109719f964048ec9c8be23c407a503b9b398b94e405f2"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "9ea1c2cafdbaaeabde55a6ebb2c7067e0586bb11847a2289b6ed85f9b00d7b96"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "b368dcf2d0059188665318a58aab661b0236473d6205a8817c1c066d18252d6b"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3a4a20085d566fa88dad3bd4a4c7228f811a264750f699848997461e423350fe"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "f3ba72b8af9a902253552edef9b4f79c94564faab33886b258ab73e593afcf9c"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "8f4ef037157b32188ca07cb67573ee7db252f17f761bdb5090475e21e0368b0f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "07d65730f91163125f7ab37f34a046078fbf53739a501bc8c0fd4c07368da668"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "c90c68883ba1b65907c7a86efa8e2d03fc043de88e9ee0226e73a45051663e22"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "762cdeb30c41a7b829ab27d742cc75d018c5ae6dfd48f799c52ad35b879ed02f"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "00f8682073bc573c027baf8b9f03168e0de803de5d31cc6faa3e01d38f3fdabb"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "d0d4d65ebe549ad4f73ba498d797acabc7c52298f9b22458ad287cfde23065cc"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "06610b52ea54f1517816ab95c39f4c3e4916bca162f4234e2ff6ea8f83178832"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "402ce406f23b8de2dd79d79ea42a7fa487e9ba6264bd59e9034da4e5cb548d7a"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "3d91eabb43685940592f101ae474d48ae5dbcc6c458bc82f8e1f019865330941"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "32fbcdb93c9059a47b9bd6f0b37e0c932c34089c3d7688c4177445376d8c28ac"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "49bab50d32d925de135d22b90c13dac55123a94d0eee132a4e859caced96f3b8"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "674064d3622274c6ebf5662d934a8cf7226243e37cb4305d4eaa49f43c053b20"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "b6e4bfc108a039b2993d91c861744da43ffa87fcf8e249dc43f7662a013cf8c4"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "694c91d6f341271b0b071a814fb64defbd52af1b228cb593595836c0d9f68151"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "3c155429e00d5ffb41986ee0f2dd843a14ce0234addb0c9dce408da870f23765"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "1628a90a0cf8611d0bcffe34695eac59fd195222a710435bf76dfb4527748a7f"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "af50c1d9270392eb8e442a2c470070718a01cbb6b1dc385c67680b0b003843f1"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "8e847baf2d1b7cb76b779efdeea766ac39a7d4109a7f03f659efd8fe320ebe2e"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "c64db1d4c76eed17029cc814781f943ae348bbc7df98f37da1e0c9c9a724e9a9"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "79a780f068e2ed9dbc08107f4426244eb8f194b498daf161cab8fee6e1cd11de"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "91dffd5e2f3f2b83f2ad96f7d7fc62c1d3a2066a84ef6e6cee3fc6054cf42f96"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "d99d85da5e60df5e8a0ca1d630da146b858be34206d39cdd00c30053c4e08f5e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "2dbd090c947f54a9a1613fbbc152578e32a1364ef21301589880bc8afa6b0963"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "cc0a9916c4079d5f9df4833087ea3613af0b8df035badd61dfbeda1413bac32f"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "0b748dcb8bf72948f90a5c5130b755f43cc3d5a8813e8d495aeb26a5a31e16b9"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9f049b1f996a54cf4609718a0969df074cc5c3f3371c29492c5bdeef345f7819"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "ba6623da01f8a7ffb14c651abdf708997602b7642dc604f3ad3b3f077aa5baad"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "a9b29e5a5da8ac1dad8f04e5354a11f15e2f413d9a185473e9fac3260c4b1b4f"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "77ea97238abfa28c31cd5398fed624da9c93ab0af44a21c9e77bdbda389bb665"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "3c7e1f069236d8cbe8d9bd3a985f17f856fd4396fbc3b46af33451d08b151c62"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "755301103c3bb7aeecc0d46e6e3c53af42ec724fa9c778698e5d4ce779ecc633"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "9cc9633e5617b3b83f2aaa0d2206948e5d69d0dc7ae500406a317be958ac65c3"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "b75bbb7b32fee782f2d497fcec9516891ee86a4a83c4a3257c2243aa9df54c37"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "38d768953f9c09be0adf5767929c83e6a2323ed3d2ed79dc3a18662c1c578fab"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "488a58979d214c3bca337b0395db4a859b99f2638d0498046bfe92de170763d8"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "d18c503a42d9c6896c03888c42629f448f0051c9f31cca522531e44d1d110a9a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f7c5f0d1e8711e621222474017e44e2de28d6df83db928f7e93502ea16715330"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "3b348a424c164765cdff4837fe8d8f21fa79c11208b1d1f7ac84ee06c3e70398"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "d54fc485490fee136d6b0cfd1acd2b8eb32bd3ef7ce0c55e28a0966c067b1522"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "9f596d728e7466308e4cd7010a0c158f77eae0f14f5d3d6e4567e9a992f51b24"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "ad404eccdcfa5e1cb8c5f606e899f5c33c0e04e5c40317d641a7c46406848ec1"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "d71946db67413349d3164199e910f3da7ee4ccc151ad8aeb0b2073afe5b09af8"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "95f662d4becbbe792b8fb9b46eabc1bb4e14ff34b19516ec7dc230e749461dc5"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "6c9db3ce06789a6f5a8cc4d5db009d9f0d352e3af47dd74794e7156f471ceaad"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "a6593be07371724816f24aacf43b84d62c2f422ea1c5dfbe8c27c77e39d0eb84"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "9010420249974c1091d820119bdd7976e1671a90b3b7492c7e7a8dd355fe9b25"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "2c889b4f7be604482b846e78b84e492228a7d432a95bd022ecd88ad0ed167d28"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "7d5a93019dce1afbe7408c4a3eab4087b898eba59168b4936c4f108d3fafada1"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "121382311667da41c1046f24e383a7033613d3d1da94ba40eb5bdc8de4c603b9"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "afa473edadc952a010fd50dd39763e66f477eaa06f5740a4f593a19a419bf61f"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "b7c3d44bd13b36eb46ff1230f615c5368e67bd780540a4ef28d2ca8179b9ef38"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "1bf292a425e8cd502411b21aac3d9189078ce76329ed5752e13653bb3e3bab34"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
