hash-format = "sha256"

[[files]]
file = "mods/betterf3.pw.toml"
hash = "2bd6d3ba4d51c4dbc3dab906491230f3f16531ad38087228946b1fd0700c4e30"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "9f19561ba22ad51af6f2a5222a5102a72d82297e821a2f67c45f45857ccf7c38"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "e5bb0712538b22ba6a4d25a63f9d929bf5f5547084bdd086cdbf99d2e4032a0a"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "f8c58a91a18f507e2c6540101f213c5379640b1e60cfe53c30afecbe360d5a71"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "a8e968c09957adb73f325d5809d3d6fa92b78c0cc2319f72ebd88f3a7905e227"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a26a0a294e686d0e557250ab6fbb9e9d82594d25f2064b5c9a29f0879babe308"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3d1a4ebd412895288db82d9ba70a82ffbdd4f811710c6590e90f8be46d674325"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7549205820740909b6e9a8bf8bc2d1b13e0181432b78d65fc0ef878e1ebbc457"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "d824964b146b2e2c6c2baa2145344b98c7e04941020824b61e1558e406bbd4f2"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "a34dbc66d99d1b70b424ca71abd5f280f302ff9895ed538ef3db8f9a148f924b"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "5a8a05b8a8eed4c1ec375f1ad3d619dac74516f16ab0c5374fc62236b7746698"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "29ab91e23d3b9045c0074fd3d15ae625ab054de8a911cd2f814a04fcc8b18f63"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "b275c235eb1bccca009af3f22c3a00425a03f8b43a1da4e34f5d3aeee9c9c4ae"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "8cebb92de829f30139acf78923985da63aea1faf222d2c1688838e98322f2fd6"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "f1fc74dc4672502add577820fcca7b0556b3c5933618e3a0cfe2fd98fe4566b2"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "1bfa78ec5d898176438a8e83bf100e58848d6edbe7bf883487f4ff339b35d64c"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
