hash-format = "sha256"

[[files]]
file = "mods/betterf3.pw.toml"
hash = "2bd6d3ba4d51c4dbc3dab906491230f3f16531ad38087228946b1fd0700c4e30"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "9f19561ba22ad51af6f2a5222a5102a72d82297e821a2f67c45f45857ccf7c38"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "e5bb0712538b22ba6a4d25a63f9d929bf5f5547084bdd086cdbf99d2e4032a0a"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "2435f8b5f2ba96db707c895b03fd815162e38226fc33af5537117cc70a6c4bad"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "a8e968c09957adb73f325d5809d3d6fa92b78c0cc2319f72ebd88f3a7905e227"
metafile = true

[[files]]
file = "mods/chest-tracker.pw.toml"
hash = "446f7098d8ffb82e23995c509f7c194faaee76c6e060cbcebe2e58ef452d5709"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "fcd08b3423d12c0ef955c2154861247d53e40f378bed0545a4cd852ab5aa7e5d"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "70e6edf93a5e3f88db6fc3d44d0f76fc41efdee58389d3b87eada29f57a53f84"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "9f53663fd88e9f085bbfd98d89fc587c53a237926e575f962b720f7c2cbe137c"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "ffe2f4694ec2e91908d679885314f05f228b77d7f6fa283d31786fc42043ffaa"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3d1a4ebd412895288db82d9ba70a82ffbdd4f811710c6590e90f8be46d674325"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7f890341242d23013c395d26df87d3b36064db0dab35ff383dff7c35cc456b40"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "7119cd62ae1cba214e910499f81e3bbffa4e0ec74cf068a3ecd6f68528dc0c61"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "aa14b6f7112843bba45604618d99a3fc724b4c8afa2053b21fc8897838b3abe7"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "91932ae751b0c8f656bf088dc347e51328a00823556d923e22b8d17959152861"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "80817a1870338708f8c09374f579064ac8a02eeb74aeac746ef1d49f3ba8a48a"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2148d404b7cf3a72a469be3433272f13218a98d0cc1af4b9abb2886bbc7848c3"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "fb65571879aa5844f5340e8af088ec6880fd6333c7536844e5b98770e99a114e"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "333663bc3dfcedd0bb207fabdd6dd4442c8549afee75326e1aaad0444aaabbec"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "ca627852cca38946410f6e03507900f0a141bb244d1df7b3fcbbfc7d2e1188a9"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "2d900464b3ed58efb3001fe22115cfd04b90a3c699d7c3f6f1895ff3565cb23b"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "c1a8eca2312a94f3674cd917d8abcb54e290417c5770aad509e50bf7449835f4"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "29ab91e23d3b9045c0074fd3d15ae625ab054de8a911cd2f814a04fcc8b18f63"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "fab6aeae99fe482b07023eaf2a71d6fe4bf54ea78cee57c929ed09edd69bf933"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "b145bdf997d0282f38103a1a797d0317e8d5827e5602333b109c0786488fbae9"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "792f5dc4f3a02223229460588dd17faac61272ba5d06173ad227dedd049fc894"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "468504b5e97c316961feade8c10b3b02c07a0a8bc4b475d8499230420a84ce56"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "6d13fef2502085e230b859ddf8f139b9c0bc3d08fd8683d5c77bf28504a70b74"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "5bff3f96f5f6fc259a38e72f7c89ced3538c67422051f4afd88fcbbc1922d4ff"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c4e20c63f116b861de0d200f3d88f7e1f3980b76e421ec9412032cbcbbe3f390"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "249f02bbc88866900297d4fa1c3f1283aedce94de3c2cd71c9daba57f5f51c48"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "981d63af83a8103524ef0201ec7fd73c1b83563891d6cf8810eb6b7b2cfd6b22"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "6672c87570175b3c3be2f2f06fc5794ad96358d983388ace0448ba0281c0c009"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "f1fc74dc4672502add577820fcca7b0556b3c5933618e3a0cfe2fd98fe4566b2"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "1bfa78ec5d898176438a8e83bf100e58848d6edbe7bf883487f4ff339b35d64c"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "dc0bf12b1a311d6830b87588f000286ecbc2e4a9a787e094b4cda6a0452a84d9"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
