hash-format = "sha256"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "710e9bb02a1a6d972628c4d5c1fe3bfac5a54bc31976ff7c9f06665b8d8cbae6"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1e94b8ba0898fb5c097c84e85c137c242e0dc794db6d3897416f0c669a1ce0a6"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "7a49bd7ce2fc30617b19d139700b8003e336f77334ac46ed00e9decb89188670"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "c7d18ef6a9f59809ea5ef3202898579d6c786eeb39ef2faed4023affc22de91d"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "f579fd976b6b0f433d674efee1ba2ed4fd1f0e9ee1215ea3840c524faebb6750"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "992f3cc0b18ddf673a133b5c22b9125545be9c97da5060b332a850e3cf417ad0"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "9c1226a35c48dd709baa5455a59930a0fc53307809e210ec9e538df58e567f2a"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "46ec2db224a3c45a3517d913a5349b2db389e67964295e00cdbefe25c4a3daa1"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "bec132aa3c148776df4f1e6dd3357657b0ace25b3104084692704cbe87d42002"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "c43c7c81fdc38a31e72558301e7e738aec0ad684a9878f05debfcd61207e0116"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "cc638912c8bf85f2a5c3c680ca0b04cfe90371e0ac0b60256df5bf98ee6c40cc"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
hash = "0eef473e8498e5967b2f5fc6caa7a0f6ecea24c8df3f366ab269040b62afac82"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "4f8fa60ab63aac6fba7b2e7bcc10bcc1dda2e0c1ccd1afbec4c80500b952efb3"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "5db6cb551ebec8cc354eed6563387be69756d44fbfd50a0fa2381be554ec49c4"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "aa98776f68d627d798959fbcfa77c28a6fadb1543837157d6e647bae2d3718c2"
metafile = true

[[files]]
file = "mods/chest-tracker.pw.toml"
hash = "cefe5aeecf8d1007a04ca1f2f72dadc3d8403e7b377a2a9460f34e1bcc19cb34"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "b87fccb2cd7144d3dd62c65126ff6d7b86c70b39d97c391ba72bfe5f6391fe47"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "68d9c6e0943edf3cdb03a487c9791beaccc75f70cf2e942175f119303caa73a7"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2f0f8b589c918964177ba287380603c1f9027fa0d97dd719700df963cf325a92"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "9a1fa7b3dbb96a9ca27bda4da0b1326b9771269b321c6b3dafbaf8b175727613"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "f3ca7c8281ad39765aea3ec76a1df304e7a6f158382462af9beaed5d52c45aea"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "64b5ef8dc285e028fb2f0105bca7ff8c16be90c2d7a092c87789b240362074a5"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "8368ca9ad3c2e8bca854ef0750cb5d43e7459cdfb2a6ffb2e72ac903d0ee9a56"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "f5b571335311651f5a00bea7b990e16e8407c4ea640f8832b12690fd10ce7f93"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "0f79537b5ac37b742f0295bb61aa16b1a7772ba85028a32aba2eca1be44d6bd4"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "c79168539da8ea30e83e7a60f127140bb1288d8436d6ad498f677f2bd27ceaa1"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "be164ffcca6fddbee69109719f964048ec9c8be23c407a503b9b398b94e405f2"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "929cbfdc3d4f7eb24fb09e8c8d468717bf95a00f553eeb5f69a41a8144586607"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "4f7ea342a5530a005cac8466d3a2968b791249a2122e0b9fdf1a5135c78b6594"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "fe5d34562c3ee0b50268f77187147a9fd94e9eb388da52b46fb8bf5d3432471b"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "5c477b0cd218ed14c178205ad498aa7f3eb1ec56444c2e760e0413e8d520c064"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "8f4ef037157b32188ca07cb67573ee7db252f17f761bdb5090475e21e0368b0f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86c2ae9ff046bf7e7efc606a6697485ea68c20a8f5388ec0bfe002ff1a325cde"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "c90c68883ba1b65907c7a86efa8e2d03fc043de88e9ee0226e73a45051663e22"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "762cdeb30c41a7b829ab27d742cc75d018c5ae6dfd48f799c52ad35b879ed02f"
metafile = true

[[files]]
file = "mods/highlight.pw.toml"
hash = "dd0c149f675a276c907cb48c9e8b8ac1ddf6e6627b6a6787e60990c8aadc1bf4"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "00f8682073bc573c027baf8b9f03168e0de803de5d31cc6faa3e01d38f3fdabb"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "1f997ba64bacbdecc08cfd0a064cbe0ae000e1fa15086ff04f24edb56035376e"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "06610b52ea54f1517816ab95c39f4c3e4916bca162f4234e2ff6ea8f83178832"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "402ce406f23b8de2dd79d79ea42a7fa487e9ba6264bd59e9034da4e5cb548d7a"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "3d91eabb43685940592f101ae474d48ae5dbcc6c458bc82f8e1f019865330941"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "32fbcdb93c9059a47b9bd6f0b37e0c932c34089c3d7688c4177445376d8c28ac"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "2525e3e87e4ec9ba93d49929080347b81c9db8f79e10b481a8d23c991674c7c1"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "674064d3622274c6ebf5662d934a8cf7226243e37cb4305d4eaa49f43c053b20"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "b6e4bfc108a039b2993d91c861744da43ffa87fcf8e249dc43f7662a013cf8c4"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "694c91d6f341271b0b071a814fb64defbd52af1b228cb593595836c0d9f68151"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "3c155429e00d5ffb41986ee0f2dd843a14ce0234addb0c9dce408da870f23765"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "4c07cf4334507ec4dc53918815f15e39d645b9a5f2f91fff7f0fe3bedb13a6fd"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f1ba5a88acf118f60ae2a7aa9b86eb5dfdbd18958f1e4856425000e4680cb39e"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "34caae01ee68f9d96e80d90e56ef012ae7452367fe396604082d57dd8d38e2b6"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "c64db1d4c76eed17029cc814781f943ae348bbc7df98f37da1e0c9c9a724e9a9"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "79a780f068e2ed9dbc08107f4426244eb8f194b498daf161cab8fee6e1cd11de"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "6e2cc7815dc811104745b6062b124395106d8940784cda88a3633c85b7c829b0"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "d99d85da5e60df5e8a0ca1d630da146b858be34206d39cdd00c30053c4e08f5e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "2c055b7b0fa6104c14e72c7ee19bdcc9edc214f39fb95e2ed7ae10348dd10717"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "26a6c62dd5e1b6812ffdf82fa05d64513100661704a3b247e7e88f10a8143923"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "cc0a9916c4079d5f9df4833087ea3613af0b8df035badd61dfbeda1413bac32f"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "0b748dcb8bf72948f90a5c5130b755f43cc3d5a8813e8d495aeb26a5a31e16b9"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9f049b1f996a54cf4609718a0969df074cc5c3f3371c29492c5bdeef345f7819"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "69d0473350d54bad43f5d07475b0e639d90a6f2efbef6921b7b29e9a85d55461"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "f0d5182f032d867f785895c314441e5484b8058c6b724187e9e3fb6019e83cd6"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "77ea97238abfa28c31cd5398fed624da9c93ab0af44a21c9e77bdbda389bb665"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "08b782e0a0be2852821480fe41375f3c648db17493d95b426de6c82ce7fabaa2"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "628c43f771521e95053e91158312081b8ddc8fe9b62a5053b8a341f58bea7dde"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "9cc9633e5617b3b83f2aaa0d2206948e5d69d0dc7ae500406a317be958ac65c3"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "687e19dd35675a56d8d7bf1387e46789e3b5db0e5347f6cf7a1652c4c341e0fb"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "b75bbb7b32fee782f2d497fcec9516891ee86a4a83c4a3257c2243aa9df54c37"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "6608b300e1a6acf3b0c84823725fca43bdbd42db16428a8382d3f099f262c582"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "ce7f8511887a22b2ad70de7dd15183eb5a73c683058ae96f5ba12d87f52e489f"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8f1db9907f748dfaa91fe66f7cbd09c5a9e9a549e23527e254a1e7c86e349fb8"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f7c5f0d1e8711e621222474017e44e2de28d6df83db928f7e93502ea16715330"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "907ff1d58db347e310f0d788bffb1f44de2f27f594998c3414f7bac03ae8f709"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "d54fc485490fee136d6b0cfd1acd2b8eb32bd3ef7ce0c55e28a0966c067b1522"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "9f596d728e7466308e4cd7010a0c158f77eae0f14f5d3d6e4567e9a992f51b24"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "2a657d59aa53b4db39686f1bdc4fe95a109d5dcfebccfdf62124a110dcddf6f8"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "d71946db67413349d3164199e910f3da7ee4ccc151ad8aeb0b2073afe5b09af8"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "95f662d4becbbe792b8fb9b46eabc1bb4e14ff34b19516ec7dc230e749461dc5"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "97b93b7c4f429050858ce44cc398106b41aa7e1b2399c59eed77f7d46c2f2e2b"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "6c9db3ce06789a6f5a8cc4d5db009d9f0d352e3af47dd74794e7156f471ceaad"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "a6593be07371724816f24aacf43b84d62c2f422ea1c5dfbe8c27c77e39d0eb84"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "07728766b616b19f8feac5b6a2814e668b98832cc63efc61617b69145b38a77c"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "2c889b4f7be604482b846e78b84e492228a7d432a95bd022ecd88ad0ed167d28"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "7d5a93019dce1afbe7408c4a3eab4087b898eba59168b4936c4f108d3fafada1"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "121382311667da41c1046f24e383a7033613d3d1da94ba40eb5bdc8de4c603b9"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "afa473edadc952a010fd50dd39763e66f477eaa06f5740a4f593a19a419bf61f"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "b7c3d44bd13b36eb46ff1230f615c5368e67bd780540a4ef28d2ca8179b9ef38"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "1bf292a425e8cd502411b21aac3d9189078ce76329ed5752e13653bb3e3bab34"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
