hash-format = "sha256"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "710e9bb02a1a6d972628c4d5c1fe3bfac5a54bc31976ff7c9f06665b8d8cbae6"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "51cc9f61e61a0b5f8baea5f2a8ddb62a12eddfa66110b622649f0f114b24b56e"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "c375509df57d1f34316b22e90ea0d233dc744d4e453b938d592d835e1463d8e4"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "992f3cc0b18ddf673a133b5c22b9125545be9c97da5060b332a850e3cf417ad0"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "9c1226a35c48dd709baa5455a59930a0fc53307809e210ec9e538df58e567f2a"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "73cfca33a3c8377cfa399216ccc4d07cb25c64942ecc5004a669996868933a34"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "2fe240e2e53c1a7f69966229f6937e0e03c59bb32f2df45d21fce6a393fa1e4c"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "c43c7c81fdc38a31e72558301e7e738aec0ad684a9878f05debfcd61207e0116"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "91459e05c6de808c4b5ee9df9d8af0a0f2931ff97876c43b0ee221e38384a5eb"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
hash = "0eef473e8498e5967b2f5fc6caa7a0f6ecea24c8df3f366ab269040b62afac82"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "f5457fec1c5ac6be0ff64eb2760fe94894fd5d3a3c80a597a2cbe81e2f64f7c3"
metafile = true

[[files]]
file = "mods/chest-tracker.pw.toml"
hash = "d496998599ebca053f2413f8adf82384bfc7e5f7ca54d08fd2e1d46bedfca59a"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "b87fccb2cd7144d3dd62c65126ff6d7b86c70b39d97c391ba72bfe5f6391fe47"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "68d9c6e0943edf3cdb03a487c9791beaccc75f70cf2e942175f119303caa73a7"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "deeb31ffb3acf692b412e797f4b325181625b09eea3f5758614020c8f602694b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "9a1fa7b3dbb96a9ca27bda4da0b1326b9771269b321c6b3dafbaf8b175727613"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "548045e01956e9e58f9b359a13dcc37b088ee1eb4656fb863ef3c11c32c9bf69"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "a42f25ab45d29dd7e5db5823499f6ee2bc4f7c1b946a37f67c8b46e844a1cacb"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "f3370281c253b8359f075df993319e661088fa69050981952459a76f4858ee74"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "0f79537b5ac37b742f0295bb61aa16b1a7772ba85028a32aba2eca1be44d6bd4"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "c79168539da8ea30e83e7a60f127140bb1288d8436d6ad498f677f2bd27ceaa1"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "be164ffcca6fddbee69109719f964048ec9c8be23c407a503b9b398b94e405f2"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "9ea1c2cafdbaaeabde55a6ebb2c7067e0586bb11847a2289b6ed85f9b00d7b96"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "87395dc93926dee2b70d08898fb871ce00a7b9b2c3c1572eb4e3232d523046e1"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "3a4a20085d566fa88dad3bd4a4c7228f811a264750f699848997461e423350fe"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "6efefdfc2535a9b9cc2ddbf550ea329c0c2b239bd8f1e9aaba8356cadd766f8d"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "8f4ef037157b32188ca07cb67573ee7db252f17f761bdb5090475e21e0368b0f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "07d65730f91163125f7ab37f34a046078fbf53739a501bc8c0fd4c07368da668"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "c90c68883ba1b65907c7a86efa8e2d03fc043de88e9ee0226e73a45051663e22"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "762cdeb30c41a7b829ab27d742cc75d018c5ae6dfd48f799c52ad35b879ed02f"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "615e97faf4824cff72415e712203fbf0534b3efc91e6f22abdd4f5f5e0fe7e69"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "00f8682073bc573c027baf8b9f03168e0de803de5d31cc6faa3e01d38f3fdabb"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "d0d4d65ebe549ad4f73ba498d797acabc7c52298f9b22458ad287cfde23065cc"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "06610b52ea54f1517816ab95c39f4c3e4916bca162f4234e2ff6ea8f83178832"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "402ce406f23b8de2dd79d79ea42a7fa487e9ba6264bd59e9034da4e5cb548d7a"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "32fbcdb93c9059a47b9bd6f0b37e0c932c34089c3d7688c4177445376d8c28ac"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "dac299cf4821db2491449dc6d6f87943dbab700ce7387bbffec09a67cc58c6f1"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "a0769144d12dd0deaf0107831e3d368a519b31f02e331bf3fd1d23def85dc470"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "b6e4bfc108a039b2993d91c861744da43ffa87fcf8e249dc43f7662a013cf8c4"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "694c91d6f341271b0b071a814fb64defbd52af1b228cb593595836c0d9f68151"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "3c155429e00d5ffb41986ee0f2dd843a14ce0234addb0c9dce408da870f23765"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "6bb5571e98db39ff7665fdf856b140793ff15c7791ce9a68902fe550b163b575"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5f5f7c3c53be65f3d32a0c2b9a76b3ba1fbebc68c2f3456ae3ce4dd979448324"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "8e847baf2d1b7cb76b779efdeea766ac39a7d4109a7f03f659efd8fe320ebe2e"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "c64db1d4c76eed17029cc814781f943ae348bbc7df98f37da1e0c9c9a724e9a9"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "d36ccc04685b101e7a708b2fa48fbb2d9f705009de266b15e111c393bc25e1ec"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "286f3b78b00f3205938e8bdf509e428ba33857cc85941d2810dfe826a3f76775"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "0ce85c644aafe170a29dca52386f48072bbd58b5a46f251995454d8650f5474c"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "444a8309afde1ad5eabeac38b12d6565b0258b0ee4f7a3479690b7c130255d2b"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "74fb077163e948ce6fffe13f1dcacba26e1bf5dfd4000d7c466cac6b385e3790"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "0b748dcb8bf72948f90a5c5130b755f43cc3d5a8813e8d495aeb26a5a31e16b9"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "d8f04776650e1786098917ac1ac384a648c1b804fb12509e05ad7885a58e1a8b"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "ba6623da01f8a7ffb14c651abdf708997602b7642dc604f3ad3b3f077aa5baad"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "a9b29e5a5da8ac1dad8f04e5354a11f15e2f413d9a185473e9fac3260c4b1b4f"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "f0ca7b5ff511d4935f578425f11a6d718bf8ae16fd712d849a72e0a77d427910"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "77ea97238abfa28c31cd5398fed624da9c93ab0af44a21c9e77bdbda389bb665"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "9cf2267c598860d70dc680f29ac7a19b419c01512ee03f81209e43eb21c80a74"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "66a1a453943320ff47853bb5bd41c35ca06a7344bb62dfc23d1faa90672f4da7"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "9cc9633e5617b3b83f2aaa0d2206948e5d69d0dc7ae500406a317be958ac65c3"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "e1baeca5b8350f3dd1831cee73a12ac370d953909ce628d662ef8a09412d2862"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "38d768953f9c09be0adf5767929c83e6a2323ed3d2ed79dc3a18662c1c578fab"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "4e668b10ffdfe412803da114380cd29ea47852c2ac4578b43f14c9b0b3c2cbe2"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "d18c503a42d9c6896c03888c42629f448f0051c9f31cca522531e44d1d110a9a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f7c5f0d1e8711e621222474017e44e2de28d6df83db928f7e93502ea16715330"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "a1769edec84f6362e0a310d15c0e1bf0b8b8102418a4636861d2ad273c6ca5b8"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "d54fc485490fee136d6b0cfd1acd2b8eb32bd3ef7ce0c55e28a0966c067b1522"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "9f596d728e7466308e4cd7010a0c158f77eae0f14f5d3d6e4567e9a992f51b24"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "d9690dadf72bcd464a485749aec85c6906215861d792261de8e7e39497c54aa1"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "7c8fc028aa2890e7ef7623dd3ba2be4b4773e83c5087dca1d8ad494f540e1378"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "95f662d4becbbe792b8fb9b46eabc1bb4e14ff34b19516ec7dc230e749461dc5"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "9010420249974c1091d820119bdd7976e1671a90b3b7492c7e7a8dd355fe9b25"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "2c889b4f7be604482b846e78b84e492228a7d432a95bd022ecd88ad0ed167d28"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "7d5a93019dce1afbe7408c4a3eab4087b898eba59168b4936c4f108d3fafada1"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "121382311667da41c1046f24e383a7033613d3d1da94ba40eb5bdc8de4c603b9"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "afa473edadc952a010fd50dd39763e66f477eaa06f5740a4f593a19a419bf61f"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "b7c3d44bd13b36eb46ff1230f615c5368e67bd780540a4ef28d2ca8179b9ef38"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "1bf292a425e8cd502411b21aac3d9189078ce76329ed5752e13653bb3e3bab34"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
