hash-format = "sha256"

[[files]]
file = "mods/calcmod.pw.toml"
hash = "23d5f6d399f07babeb4bed1f31756a0a0b70a78433362a30e2fbad67114952d9"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "3d55a97429013c0384c818808c5b92bed4f7ecde300a2682d2471275b72c450d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "8cc048340be8ac373b0a9b29afa1a4cd5e194698f37d7a45167f21497185a82b"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "193809c5ddb7edd3ff62539dcde50e4e8866e75247cdcd511b92761b8f3bf4fc"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "b03ed3030f06ae6b544e5abc92df3be91d1f617d2302e578b2b55fcba01ef4b1"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "2201f39c79e876eec8c42484542bd654891b65bfff7b04f85252a4594d824633"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "2d6762f5e12ca0feafe8c8978b3005e0428210108fa620c6c87955e4daa4e5cd"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "43f1db342b0bcecd643db6963099473d44a85cefe6291800686d9c6bb48428f0"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "89c6258ef91cb3b61a6d20801ab420eead9b2dbfa960fad6dd2a428234afcf2b"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "c92359c405808fd391e4f8ea93ebdae01911b98d2c5baec2c41bb897b748a6fc"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "04d04ca1f3d714fbb84a9255f974c9eee8ebdc991900977fa63a6cd528c0946f"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "c05b8b6405d9af8857cc2a8db94014c479417e1a461d3faea356cbdb527e4590"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "1f4c3d1f8100c227e7aab2c02502a53fe489329248d424ba90a95c96a8e5ecf1"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "0279a4594892da6d237672f962fbc9977b92181389dc8a923e293cf98596d871"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
