hash-format = "sha256"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "25f324cfede1cc501d10970c1c9057a38cbe4968489c26541e0eb5e952dc9cad"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "e86625fd9efcf4363326b9b2ecdbc0e45383977f57b54e5daffbfc3e271a32e1"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "f092d8712a9610aaa76da1a35f9041e76db188cd6f637fbed5f136aa4041ce81"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "e54ebfc9d7640ad2b2d98b36a1c63b169bc81655ed50e946df4d57cf333d60d0"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "f579fd976b6b0f433d674efee1ba2ed4fd1f0e9ee1215ea3840c524faebb6750"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "86ed2b98e4fb7b48e294a6352062644c7471f1c2aa7dbbba50bfeac1c12b6cd2"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "ef10580079117fe7888cb2895ed6bdfc50060d681578da8950e34fa3e6205df1"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "c9d8f909d984837080074d839dff59ee56a91debfc6059083ba7726e68fa841f"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "a3b5f31fc0b6c48255225f4182edf1c3deed4d2e2779c7a8a6a8af81dd006f35"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "ec5e95b54d57abf8edfe1ceccc6d44de2501657d4f228140c5f768c3691ce505"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "fd61e3c27d2eab88f18928f6d0590cd9fa44f4c309c45b017268b0610c6e150e"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
hash = "71c05e47e173658e6c364733d1a9ca6c79ef1d94bf0c3f186f18e2d1c6b77982"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "729fc3d34c8c02e65f3dd078a82b4440d3f8333507f1b09857b49af64a40e039"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "42a6ce5615c435e3dac7f159d9a0d29e23e4d70eb8ba01dc3f3e1931c2cc895b"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "90321339d30f8e37b9f0ad7a32e3d04b38aa19ae5e48e438269a682b910467c8"
metafile = true

[[files]]
file = "mods/chest-tracker.pw.toml"
hash = "a8964e8c850fac3afbe955a1d1276fb1d1d372fe6b5847c04117c596c206d79f"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "c662499ef7bb6997ff4c7f0aac21fc84dc5f8a98d0f1466266ba029c7df4cf52"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1ef632e717cddf680b7e21e6da770234b13aed985e210f3ff7a6660a77039038"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "dc3214196a234eb4c9d4c833185a02f7e94ef664abefcb17a4726674129f3cbb"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "1816f4148a75042da56c9747fbde9de55f2a17c2fd21223dab65059d313e5aea"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "e6f6688f4f29a223bd873a72b492eeab0ca94ffd6c4f7a85b1c1720964e7e0cc"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "228314ee191a7d5e15e66c5e4c5fc8fdbb1261c8371fccf9dce240b18b31b5c4"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "8daa6333ae3e9c18f9a84d3091a4a071782ac8eab4d78e83121c957a45b9d67c"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "f3370281c253b8359f075df993319e661088fa69050981952459a76f4858ee74"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "112067cabce524ef760ddced8b3a88ce0d864674aa22976b0809cf6357ed9bd2"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "c8e47100f8c4793188b72db87c4a3c765612bb16f09e25713b700d4ebe5c7a0e"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "3225417e9645675921ca53f2e62ae6187287d1979558a9ecfed782069763cd29"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "694137b4f739a22ce5cb83c0c7510ee0091c96659315f80767699e9322c090c7"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "5369133a7acb941500845a1edf4ffc6d4297c63e69857e6cebdf342edc9b05f8"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "810f1eb2aaa895b9ce0bc65a0634935a79474cb31fdb10c79896776c8b047a9e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "52aa297d094b4a042108f4c85d08440f08be1b9c5f7d3d3e906a8f858fe080fd"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "268b09c7aba30a68dd7bb5385b2f8e3f4b0dfd8d4d1b6c8fcc5245452fbde419"
metafile = true

[[files]]
file = "mods/female-gender.pw.toml"
hash = "3e7378c1c2a296e9569a7f159a06ae4e3be18aa80ff8e7eb32b5c567892887ab"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "677d856c525cc375a9d74289d6c90695ad821d32ff22290c09149c44b83f3edc"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "5d2ed4d4148e0d18761d0f8a93916ad27aafe816958ca32dfdad698f3c49cbf2"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "894999bb6f6c79e4d47255f9f3e93fc4d0dd9ba1ae0f599f6035bf49d9613a76"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "34e1e586d71c89b2b31fad65e3d0f10c27c89998d0cfefce4bf33f43044c0067"
metafile = true

[[files]]
file = "mods/highlight.pw.toml"
hash = "847b8459b2779daa0b7b98afd8981cf52deb4194964f4d9530bb3c81afbeb678"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "b0a8da1ed3b96a54cca02d9c3ceea61626b05a6bf0272a96d82cd9d026ff9607"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "e36170d99e4ea9d1a34fde4379acfd9585f78ff685aa812a68b770c6a770d539"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "06610b52ea54f1517816ab95c39f4c3e4916bca162f4234e2ff6ea8f83178832"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "17c125b2ebff0715842e25e38671da29deb0ac8ea0d3d6579e788a1e2c2dbda3"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "494501c768dc541bec24844968396471b1e30ee813b34cf5c6a5eb68d4f28a09"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "0aa78eb9d3e66d094449fd5b6e80d002689c5954451813e2ebe85ba84422ab26"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "38eb0c898ea1116785f16e3241099284e042d1539bf73bca554334ff61ce4ef8"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "674064d3622274c6ebf5662d934a8cf7226243e37cb4305d4eaa49f43c053b20"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "69177f790962984c00e65759a65a8662deaae5a882b9f0bf8ec54426b1891d8a"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "694c91d6f341271b0b071a814fb64defbd52af1b228cb593595836c0d9f68151"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "67e3d2ab29370f3e4a2c24c29fe9055fd54e3f5912730f9f480af542ebcbdc93"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "824ae6bb020480ed481e2289b8e71a174f859925b0c797847d78c77fa4fdf413"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "78e80cfc00bc9fda1bbafbdbe2579014c699c94307379223e56c391579f1f94e"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "34caae01ee68f9d96e80d90e56ef012ae7452367fe396604082d57dd8d38e2b6"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "c64db1d4c76eed17029cc814781f943ae348bbc7df98f37da1e0c9c9a724e9a9"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "5b262b983c1f9bbd473cc57fa06a1b1d02f366c86562706d202556be117098c6"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "77460ed7cae2dab5eb92c2d7133f7066e8274b025d0b52e5babd0be60c80e461"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "83454f7ce4c27a04aaaea45ac85d320551836efa574e7d7a83d1de1206e05313"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "72dcc685b23aead3b937261222f3e61c5e9191bc9840b1246e1f2c0349b06202"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "c4d9b5044b2c74b96fd2b4ae64172c0855f5b75f9d801f32e45fbbc973186dc4"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "f2985b51380f83601b85c4c33c0090ae41d1b6e35d81ce98e58d8c1bd4eb80b9"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "0f5f70b1028b85c6b6253b6db518733c594f776e72c1ae3023953968741ddc84"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "7422cc0347253523299397cf2b07e591edfccbd8516c23730e80f999b4fbda93"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "43c1249516f401b13c6943fd41297fe65ea6536cb4fef44a44ddeceb40d8b8d0"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "a442b4f0e8bedbd8967c5394b8cb03d5bf59f426f3de7cbbf7716ba197235812"
metafile = true

[[files]]
file = "mods/pistorder.pw.toml"
hash = "ffbd91a143b404b42b9bef24ec8afbae8310f73ab3494ab107f0cf86aac37723"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "5e4ddafb4ec3d4d82442d8c4ccbfe21ab6eb4e3fc658f38ef5e3d35d150a1b03"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "270cf4c54c809ab4ebda74f6e09da187ad847c7193e7fd051ab8e44213571ff3"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "59798f640de54aa4fb193f410ebdc140994442d12ff8e49ce9e57d2429199eb7"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "9cc9633e5617b3b83f2aaa0d2206948e5d69d0dc7ae500406a317be958ac65c3"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "687e19dd35675a56d8d7bf1387e46789e3b5db0e5347f6cf7a1652c4c341e0fb"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "0b1aeaa0068c9ec896bb8a8aaadc9a345d4ae45ea6ef09c1e5f1f4f9b9d06cfd"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "cbd7886c50305cec106290068840f4d7f376337e2b4dcff387abc0fb65c1c7a5"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9bd4aad7a61dfcdce598c24be12ca9ec5fc0db2ad8b7336305b084854d2e725e"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "bbbbe90327c8a4e77f8a77c57d5304997bb94c1c43b31ef0c8002348c2dc3791"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "7427f317ab9ee3678426f7c8653fa638602323a6e5f7d9dfe72bcf135b44ffe4"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "35f71aad713bf54047bd13d63ee1ba51cbfa3849cfc7f18b73f210b9820b311e"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "d54fc485490fee136d6b0cfd1acd2b8eb32bd3ef7ce0c55e28a0966c067b1522"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "339f5e4f18c59e538a36e3bf30c2d28b95500efdf4ca0b63c989178c35f8bfdb"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "3df12ffd56732655a38ccc29dcc269a43381965d92ef9359650bb79f63660a25"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "181fa64ee30815df4bfcd21a3203c99985735b347310bd46a4d3a16139aa7df7"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "10d99f93311d1d44df4402c32166ca1b35ceae6e14dafe4a2dc3992ca485f968"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "673a4652eeebbd25acd234868ef9b5ddecf686f56791f7d99f28857ea48c8d88"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "73f457af041340f026128ebe3dd83a05aa683b71b88ae23e51e1da69638d2ae8"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "4b789c252fc1900b47d89e315b6af56cc62ac581c8bd4ff4cbc021677e6eb90e"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "2e7d4e9108cf5ac9ee5c9e1e20e4be6ae033b1761d1ee9b85e975f52363d04f2"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "c862f1f6015cef861be1e5b8f233ea546e8a77034b521f9d4cebbaf27b040eed"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "606aef56da20652fe88481c64fdade1a4998eefe7e0afe7fc9bb10c4d37021b6"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "afa473edadc952a010fd50dd39763e66f477eaa06f5740a4f593a19a419bf61f"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "1bf292a425e8cd502411b21aac3d9189078ce76329ed5752e13653bb3e3bab34"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
