hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1dc74cad62eea96232cc197b3d1e54de4ae63f7e918e56371dd1613fe24b7355"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "2b4360e14dc5f3137c481ddc682a3c6d0d5d3162222c5f306ee915e25ca5eae5"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "a174ebfb74b63cefdca6109147ecd37d330174e44a64364cf9e1ab07778062c0"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "fe92368ac0942a8dd56ab8c6c02eff03a3ba0d8d4a5d74b899509a7d962dbb6a"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "1e7df930a79ebf3a24b509dd9c6809cf592108cfc1b07d88cb612380d72723a7"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "1a53593054723f1f7096da9ef8cff1564c7fef4a1940eb4174e7f8d9ab5bcbd0"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "8955c18149c29508784bf262cb857605fcd22188e8f30c6ef569277c1ce9d8c0"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
hash = "5b48a918620ddca185e620307ab18a95d569cbdf85f303b4fe825121f898ce7a"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "231ced0658641fe80821c9015ef9cca167254af2c9de279a47a997d9aaa1b891"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "dbb14bf523fa5c96cf55135fa1427e6723f8587e6b65afba7f6394f1bdc74cc9"
metafile = true

[[files]]
file = "mods/chest-tracker.pw.toml"
hash = "922050d1fe09dd94cb3fff63e8f6279f08b1964e1baa6c6f76b26e3eacad9465"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "f6ebc2055e809ba8ebf2f4c2ce0127effb2bbc6ff684909d352aed66e1f4eea0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "379c3cfb0a775914a1a66917f710cbfa3baa3e62cade49b5ce9bef55d158a4a6"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "b130a9456d0a8fb9c3793d24e314af54b6865ba6fc52bfa28f3e86ec581335c8"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d4e3fd7703f71f9758367dd3ef0927564726df4d210318eda44ffa985e81d736"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "fb936fa7482e79e2c50c6e4c7b01761d1dea09b092e11a0870eaeecfb5248cc0"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "beb8b7166f9793cc9b37ab642254dec211cf48d4a571e64951d752cd3ce63f0e"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "dff7ac0c8fc0398c3d5beebe80fc5fb56e4267cbda801045ee4bf49306d7d2d3"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "bea1d0d108d827902569b107767d8afd055909fcbbf587d31ff33888bae7dff1"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "20dc586c928d66360a26e6cf9fa4e61b5110410ed43afa25bfdcf4e3f611c061"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "4ae6fae62068fb41d8a8db1515c566b09571878c4bcdc71984d2cd820ba5d333"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "b52725c6e0cb03c6a760b62dd7b6abb2e7dd85df08b0bcbcf2af5943c7a49f25"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "1e9150f5a0ce27ed1e3218794c62c75c5c87b5c1759f48bd9339583c8f492f62"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cac73ca610c040c79d9c04efd463a246a6f59bfa929d4f5da79dbf5be255b32f"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "40bda9dda959a2f87d990732eea1f63948c50ed9a2a53544f8ee068b33ee1c7b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "ee1384200c35fee039a2a6f95a62a7de25340cd831521a0a90ab82b94b36e951"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "7c4f9fbdbba973237b890198ee2c632d5c64306549fde04c036dba2695866e79"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "b72beb5cb53e0df825f05d6e10a15284623127af850b144ad6c9709fb13a2afa"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "f2a2f018c5c9ab78bc7a47ca3c5a5c6b3653257bfcc2085a3ac68db444d3fd6e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "51459057d731fd7508b48ab92ced48499346ec712b9c8d4f6eebe20c9dc2651c"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "42b56fc173e615ca156ab89f3d196f78b494a1de9a1825910c4a4a7c42b7dab9"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "c768020ae2e21660ec0ba1fd6f490763527b60dd3a5eeb673934549e59a39e99"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "830393c310b5ddc3afa0188c69cf0e3d3dd16d2c8d15fda103c1eeb0bca42381"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "507f74512f1cb55505366e56c45108864ce04cbea33ca2bbe675a90a37668a2a"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "2d7ffe826eb733f7ef787dd74b239b458c6d18666c56b19a998cbac3fcaf8222"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "8e847baf2d1b7cb76b779efdeea766ac39a7d4109a7f03f659efd8fe320ebe2e"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "0b754d32d37c6bcbb5a97b50eaefc296aa1fbf1735d9af4a7fd671def32cb9c3"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "65c8621529de7d535340642db8f08beff7d5bf24d7a99b1ef2f90000bb16288e"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "161fc45ad05575fabdd464050d1bb6e8dcd8b3083fb215d539d152e9c6fe7548"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "113730a58c9e46dbf8b17632baf1fbafe4e24ccbb8d8b3e9898bf3f5a38f435c"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "a2923c92691b145d8671cbab7a496ca7a679dd9a0a44ca9af88aac01f44dc469"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "3697b98974ed9d6f0f8f86734d80d612bfca512bcfc93be8b4a43c8f2fa3c918"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "0cda538033788e7b1190b3b4d3fa23a8950d94f91b51310f83ab91ea7e5e7a24"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "424d62eea59889b59c9b5587c1459c2c1f93b68ba73443af981c85c1cef66f1f"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "7f09a6441559ee709800a99efcc3507fdac95c248f55a2eb7ee8f5c7de6ffbe5"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "bccbf73e83f8148d20b4eba5c4bbd33b4a3a908dad023feba3c8d1db7d6b2569"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "13771b3f0de6f1cca4d2a010ba770d86b2d647df5c56c2281bb7ea356d7e912b"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "d9aee3833ae4d543f820fda7f7989bee36b34556d031e614b2c4ab7e82620ff2"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "5075772235289e3c6d8750a398b646a05290fcec3f8c71fcbd6b0f08190d2762"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "3d8d51acdd46e5cd60b76feced0e7a4fff823324cdc72e56a16f6e725c9861e1"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "a991f3c5c1001e4eb4d2d576167f4818fa5d35458960f4f899a215c187a40d46"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "7e7cb92ba2a925fa1597f2eec002d8ec8f9b1380ff0062757a47e5d976e74ea7"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "5ba86e2d364b67520c81d108a260e2f4d81022f6eb66cc0fcb07d2978e1682ce"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "3959082953ee929a52e83b70efe413cdf2bedd8979470c1e100e95fb665a48ac"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "05e86d99634d5b81b409aab7dd95495c86179bad91311013e2a10e74239b5753"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "2e6fd01696c404b4f0e013a4e62e661a0767e37b90d3630540d52ee151836012"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "1bfa78ec5d898176438a8e83bf100e58848d6edbe7bf883487f4ff339b35d64c"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "d9088bec9c98e2835fd39303447cab1202c4ce66fa24b833a5e43199aacda346"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "1bf292a425e8cd502411b21aac3d9189078ce76329ed5752e13653bb3e3bab34"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
