hash-format = "sha256"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "f34b45f41de22183bf3c2ecc037cf6ffb049658575072b191769805a63e1d618"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "89ecc10afc650e462f96d03a9bf80642581c09ee39c23488752aa064ca8b9164"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b138c7b832b037f83d62d6a8ef0d06da8394812bd8f5f554f888cb901d11c4cc"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "e54ebfc9d7640ad2b2d98b36a1c63b169bc81655ed50e946df4d57cf333d60d0"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "f579fd976b6b0f433d674efee1ba2ed4fd1f0e9ee1215ea3840c524faebb6750"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "8f009ea6a8f023d35f23206cd9d13c56c729e6c92f3c9d89dfe1005268cfb1b4"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "6ec72579e0f1b7ac1174b0c8497510cbe7dc8f23a62194304183fda43aa5cc28"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "54330defe5ff939511728030cf82b8d8827a5de4f1eaebb2479b856f87c38ec0"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "08b4a962ec7588ab5ccd9d9838b6c3f391b8af9f61a56dd2dcb54decd0ebb13d"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "ec5e95b54d57abf8edfe1ceccc6d44de2501657d4f228140c5f768c3691ce505"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "1d7cbb1af2b1aea06cad108f04b879c60ade25de13d27dfed91b78c9b42a4ec7"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
hash = "10954a7da1e319a4534059551db54d17b48d9b336644cc7de67943fa6b48e745"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "ce42c849ef13a91851191c4e21c0326172a8bd406550866a1af72e71720786a4"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "c7669abea0e548ebc03f41d968af592f792aebb56b5be647d59c48457c3b301a"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "90321339d30f8e37b9f0ad7a32e3d04b38aa19ae5e48e438269a682b910467c8"
metafile = true

[[files]]
file = "mods/chest-tracker.pw.toml"
hash = "79f7606144e0e5f617f0523f7d9cc27a3d442d90a7cc67ebd573a27104fc71ee"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "7acf38db94d546ab2a048e2d0ba077f1d80885ca1e32642ff4a1fbb59aa3f342"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "79aaa3977274f2dfe851592d25237abc98fa889a3b9c0d1ccbc1de295e115b26"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "24d26ab4b9ed30b1f7a3c9e7037e63bf6752d6da85a0aea7cdfcc009ca481bcc"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "de26cd1f8d8e16df0bb8681cae36bc02fba5c4f7f4f854928a6102300cc321b3"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "f8f98c79560bcca9e9dba55377600de4d2c8d4f5a5146ac304af4b3f972d6b52"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "0b72bb07d240b53e26e4699a965ef8ca61af4bc26d1ae7746240c1f4e6caf255"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "67bea44585598c0c1b8116d20b6476c53afa17022889f6fc500700edec847950"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "e4faeef5645add6e66151ea15f289e2f6cd8d12f935a8272e222b7b201728e63"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "112067cabce524ef760ddced8b3a88ce0d864674aa22976b0809cf6357ed9bd2"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "eb73ab8fb786d19f50407ec7b2169a52e192891d1670ce8ed110457a88720623"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "205afa1d438ca408daa883e86003abcce02838412ed877814a71d55d9f040052"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "1c0c020a499f58d36d68a46ce8354d4ad83692466f4cb5b0602d4a5a9d2cc9f5"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "eb74df858c1b38252d7a88751d40b4d530771d4272983e384d95ff2fed6473fc"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7dc6857294c873da4eb294c3c686eb72d9dc99e68e24062014ee475d1b153997"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "b01b73b7e30086bd19fb8c290ecd54fe3048432d4a17db21434bb8ef70eced7b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "fff1e00559f13c092b17fa83804279cf70191d7a99a4a98a4eb6bb30ac9a78db"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "637fb63d9c6dd7f66f9a734f74f87fba9a0e1a43f9cb4bcf5241bf19fe0487de"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "dc0f3025dc000004149e66e2471b21dbe2d9ff9a157fb37db49abaef7697fb85"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "41d7addc17bd8112b47f6918782447ef33c8efd0ba74f40b546ac0591a84b062"
metafile = true

[[files]]
file = "mods/highlight.pw.toml"
hash = "aab95bb2bb18096de20d9eb16fd44b63bb0602247491b33517c19dd468525e23"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2e704e5192aaeafcfad96da3bca1ed35268f3b09beb9f91f398530a2596ee16d"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "f3aebff50fc3e87f8441cb8e0f295968bbb3059304cfbf523ab3d5644dbb5cda"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "06610b52ea54f1517816ab95c39f4c3e4916bca162f4234e2ff6ea8f83178832"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "2b89931c136a95ec10a357e12d75faa9e8c9c5405c2a43ad5b1d3ba0318e9a10"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d19d26b5ce69c4721c4313ae3a3fb48d47b540b3215e6fc8ef408a59a28af83b"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "f6c15e333a5bdeffeddc2a4d0a130a41af2e2f564d421a901d5cac0ae5d61e23"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "6fea9fc46230a74793e80fbb51e2eb3994955585037932d8a114ecbc0ba8ae88"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "9dd2808f043c1fb8dfcf699174790d6f082b6d56aff1fe4573927d8a722931bb"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "b46a4881fa4d1cb5c981bdb4053ff38544da3787b49142e9893e9745cfef7dd2"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "694c91d6f341271b0b071a814fb64defbd52af1b228cb593595836c0d9f68151"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "0f2e9016b1e4e27c178f52c4cd62dde4005817abd3f1ccc50694dba54cda7af2"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "1b18d8466a8bc7927846bce45dd4383178a9c71a7461260957ed0056e82df9e9"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "78abf7fccb5086b0a7353916b8e61cf52333743425f3f1f925ff5764881114fa"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "34caae01ee68f9d96e80d90e56ef012ae7452367fe396604082d57dd8d38e2b6"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "f531a8ee70e9d78ee62a84e3fd18088070dcf8f2cee2384a8aabed16dbfafe6c"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "d77892679408ebbf739ed7dbea75d740a54dec106bffae1f1a5f35158429e34a"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "dc7a8014329d06fac1fdaa31997f280e9028d5ba9f9a28fef43aba91757740d2"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "83454f7ce4c27a04aaaea45ac85d320551836efa574e7d7a83d1de1206e05313"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a63b58c7f98368327c83a77b58f8185322941ab0b722d06a21cbd68ce921818c"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "1517a373ff7b6c90391ccb5d12b4013bf01bee2640bb1f03125f42c2ccbce3cd"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "46a0664543eb34cc569ee5312e24e2c8c73e20ad3471bcefb5634457bb87ca52"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "15aeb47d821f9b32aedec06c341648a351fdb06c6471424a7aa9652f643dcb96"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9d8f4ebc003095880b258cf8cc6923ca5261e1d8039f0d3c3eef1f9e31a1ae34"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "9c3cf05912dfebb0695e5b780532984ac5c41e2440998ae943bc80e8288f357c"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "db75305a74e6079ecd99435808886ffb78de8d2cdd3a6509bcd8d2c0e5f89e65"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "f0baa8708ef16855f5bb5ad67578e67a003201331702d54bd4d84b25fb529a61"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "b932457446aa5478f2da0fee360a1d6c24130ca902787dc3a1a9f72d5b5eaa53"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "677a669e2b404244af6026ea3cad4f47de1cbb0b538339164dc73e993bbce614"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "47dad49c3470e2bd93c6ff92986010e3618fe9616c10b8e8520c68cf721c6274"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "9cc9633e5617b3b83f2aaa0d2206948e5d69d0dc7ae500406a317be958ac65c3"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "73feb18cd4688bad1dce10532b9638c9a33556210259b847cf3bed736c6ae1bb"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "da6ff084c7728edba668a24ba89230a519c71a02570c0e81169ddd4505674c06"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "4b7ab1508d37d27b4789fe49f0ec2db68e344d82ec12437808c6cee9c691bfbf"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cba039a465bbf9c806b2b3106f7c6b905e371ac40ce3f85511f1f1df669c9883"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "11730f00e462b590af8efac554bc8bd508f7a026e66ad27475b008aeaed870ad"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c0d2a8f6068419557b957615e7db354a0e0caa994b18c98563307a9feb8a0b5f"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "15b37201c6dfa7bae952f275dbc8d1145c0ab8471825013c177e2f423e63bb71"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "d54fc485490fee136d6b0cfd1acd2b8eb32bd3ef7ce0c55e28a0966c067b1522"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "339f5e4f18c59e538a36e3bf30c2d28b95500efdf4ca0b63c989178c35f8bfdb"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "1b1da6f11d2a97ed47e926810d2294d6747fb2a03695e1e5338e1206d1cc0a19"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "b4646dfaf9c5d30971d9f1b55a968ca42988889b091e2d777e0b36a31570a1f7"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "35d79825e2cd6a7a5c6d07bda8585ebffdff4c3d56fa8666baa03c65c0098486"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "0eb2a6f77ee3d03d606f4674fe854563362dfa39eda7fd6a7de2856735edf1dc"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "46ec45740a1bee8bad579812c85b8cb0580c8095a737aaaba9963bfd727f67ce"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "dd9eee69a0eaf2d1231ba6382426e20b8b38cff30ef03bfa456c7983eb1b5c23"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f5e867e1ec8b1cfc0453a690c53be70948c261b3b6d0c90743a22ba0ef1fa748"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "2e7d4e9108cf5ac9ee5c9e1e20e4be6ae033b1761d1ee9b85e975f52363d04f2"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "d9e7e1d2dd19b04f1eec52c21f8ee8a53cea2f27d56cc4adbf8a40158b3fe7cf"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "64a6952d057e39b8489a28b2d08754b1309040a8b4b95302d02aef6b44cd627f"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "afa473edadc952a010fd50dd39763e66f477eaa06f5740a4f593a19a419bf61f"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "08f9afbcc9ac33e14ed81ee3ea4143720b676f9c37d6a8c53bef67cbca8ee631"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "1bf292a425e8cd502411b21aac3d9189078ce76329ed5752e13653bb3e3bab34"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
