hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "53555f40aec0fa488a39ee945937491c3c52f33bc9093cebd7b8bdd3cd1156e2"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "2e73e40174e0681febf6a78f7815cb6cfb24093f3c7c354389c5e452f8be0de0"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "22ffac5e9696e4d6f77a0d4cd8d9389b9b0496989fd3c3028f2d83dfcd616bae"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "756076f16187411cc3723ff9bc94688e23714741249e67369c4f9f7fca65ee59"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "be08023fa25b8092fdfe82485782758e9e46eeded122d8bb43207179cd948c2f"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "663ebbf4d38d266f4b3902f9f904a2f3cdcec912a126d2886f311ef30592460b"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "c3e2c77b0d55d67aeb61e50d46aea35c50f7f51ee7026305a169f8c5c28c0942"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "837bb9b0478feef852a7ffac8940a28b9f069cbb24fe2350701f379492462a97"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
hash = "062a9eb22a7c3d55e11e212f12d4a7d6fa67412898bcb3a2be2bb170c2495174"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "b1d371f5219331ad95e6aacd9bda0d677d87ec5ec4cb498bf1a286f8105632b5"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "5b7af7fec5ac947db2e53986ce6fa0e56e62b6b5b76a0b9fef698898c2907480"
metafile = true

[[files]]
file = "mods/chest-tracker.pw.toml"
hash = "82d58a5b7bf8dfaf5a91d7bb6fe14dd73eb5ee94559d51259631c971adc7dfe3"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "763eff7b734dfb8a1648c548d17e8dfc2addf2222a5dcfa2d9499b81c3cce7c5"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b7e1ea2ef0d8772b56e160ae73880de0249fa0eb7c6d1aa6b3f53c8c92f9831c"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "29e0144fd8f4f2bb0e5d702b4505a8a5e1c008ec24b41af842a335918f3c08d6"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "a02f85709d84172e18a6a33fe431b855008d7879b207771f3e558e266202be8e"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "5b2c53563bbae0a8f8ffd98f0882cee7c24f3c4131499aa6f54fdeb7c3a52fe4"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "10366094adf674a21f68c2dcd4580d70341f9773e5a855eabb7ae51f9824eac0"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "9e920a302db870e570f6f2a3adf1212b5965a71141907907a94efc1bb222463e"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "a1095d36aa401ff208298a279c8b9faad51f041936164926012f20de0f3c3ff0"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "87288a94a1de8d176f7da2431789b8a46b73d278121a8cc6145e67a2804f92df"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "49313d469bceaa834b58226e2df59205fe48894e67854fad41d83cac2566ec99"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "897d523fd4d02e925a8e0e2dbb1b951751d1e6e9ddd882aecebf00cabc80ee04"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "175c479fd126a4a257c0af0cec14ddf549872438ddcf68b1fd0a508a1dfbdf2b"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "767eea9287ca8b5f73fc9778d8fd653ebe8118bb8734c8b370bd255c262fd210"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "e4c72ed6cf4675d6d024c119f6004a32532d135b45a1e1b69781b10086890331"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "532edc0d0e1aadd8b5e080751467c95c6ce8b3ffc4d642a7e81ec688fc09082e"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "f156ce6aae087330abd6b76fb35327ad14af846e1b85efe1d4ef5944d971eaf7"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "cfc005ff92ebe917b76a1b787926e71e41c40068069ef440fb385fbc069f410f"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c159f880c453c8eaa00433d78d4b8775a1fdbba4fe2fe430b4f50a84554e053c"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0d8a3e9884f4c82f445f75c68f0a4f12c613ae46ce6a4784a844fb575aa8b6ec"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "01f54d293d1008f22f8cfc9a43b4c8e5473d882c2ed7ca667cbcf55ae4d638bc"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "c768020ae2e21660ec0ba1fd6f490763527b60dd3a5eeb673934549e59a39e99"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "43b0fb2c3ee59c5be20065af0870804a22f372b799ac0dc43a432df129855dd5"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "609e5067280141ade05d8e0a8641ae1c2ac1f36ba26223acb29af0e677d5c833"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "e1aea49ed8a6f2af853793ee649e69d27d872b080c4a4a30264a42022a4eabed"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "10ba79b284904a960b950cc96d5956c2fe2b0e587eccac130912f71999e799e9"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "8b1f5ff6a14cbc21bc879bc773f0d0d592434b4eb7cc99a29f5b753a21ca16c4"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "46c276d92968436f6dd9213c1283669c25a219fe00fbee2360c27630a1ba8a3f"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "682c345112a0296450041eb8529bcde162d4cc6fec0cc92621b21485bd29ac78"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "04b16c8adeca9d044488078d051d98177bef5a19aeaa8dccb75c19f5ffdd20f1"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "2f466219ed1c7bc5dcb9ca19f9e01ff8f83b3f6f922e8219a94e2365c3987aa2"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "60cd3cc92da959b12b1bf8f4774561c3ec712221fc7b101ed4267e1e1b8dda94"
metafile = true

[[files]]
file = "mods/pistorder.pw.toml"
hash = "6a4640382751b9ad605dfad58822bd65344ca4782a5da018fa45863d4b8b57e3"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "a7cd730b256f590cad6e32b7fa6c2d52dd632c58fd87a7b4fe4d21f4377f10d8"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "0efb8b1fcd9221d3b18a8e59d21b74de65cc854601c3572c76b6143c43bc49cf"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "0d346a69981ca3e5580ebcfd8aee14ee6fc3c0506747611631143748c7301308"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "6d13fef2502085e230b859ddf8f139b9c0bc3d08fd8683d5c77bf28504a70b74"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "0f768d9ceba8f5c9ff250a7f9b6083d9d472feb76f99250b6dccebef302b32a1"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "c71764e1c3ce558c797aa450aae62608129c5aec911d7b44c552f16e76aa06b5"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "1f91747b659019ecee0b99455f9120f00f0d98d40b48b5d43ccd0715c39db85e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "df7d2eba1d60778975ea3bfe42c119d62c04363805932f9f034734c4f03236b2"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "509dbb618e183549dc515dc8804cedce12ca2901fc68b34b99fd002651691eaa"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "d63beb4cff57822beeca29bdc8bfe1ded481d14146fdff27df57aa5417153e9f"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "405aa300d3a64a33626a0ac7e91f5af5d1655de554c2db4223d4457ba1e8307d"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "f56b04da18f427ae4e55101c8b3fd300a1f99564e0739d389701ec2995552c52"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "2a460964fde484d183d59147b5be70dd0a3b663a58060073af93900aaf40a97f"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "6b9999b27fca372f9e1c464c5f5b8351c5201ec3c392e7ff3f69c6967b51619b"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "1223c59c2c85c03c93b489a8c6bca281107c06211220ab3378667228bd7711c3"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "1bfa78ec5d898176438a8e83bf100e58848d6edbe7bf883487f4ff339b35d64c"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "6d2a64d446abe206138342e4b5ad7ffa5ad60979c684d0e67d742fa0a1c9ae7f"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "ab7a05239a62648ba3d0ef0867341fcbaae505715ebe0748922fc70f8cb23ad8"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
