hash-format = "sha256"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "7676ebd8db5ef5168bd4ccda3145a8c49f76d57e27fe839c9bb60964902a8859"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "333dfa2b93c688ce5f9f685f77cb62e5df8b9c8d21a2c4dd4eb9232aa85dccff"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "6d7c5793f88c52421dc11f48b3bf12400e7a451b9297e80fe33b776cc2af2c1d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "a1e024094c28068c99a6da1c5867cbd4e66a315718039659bfa533a138762d9e"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "04ddfc50d957ad8cd71306a19b98b3b64d5235bb1c6a694592087ccb1f0c0dfc"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "8982ad6fd8f93072f935abefe2b42830441501a760988f3f47bee0648d4f627f"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "ce81c3b353108787333972eaac221fe74c1e4664de39a7d2d0ab202f6a142dc6"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "0cc9069aeee558e036c7afd064d37d9f468ea1138705da0fe4aad64d95312f79"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "ec2c437fe50a3f8ea6077215974ba9f769cb94eb29432156cbbe43137a74013f"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
hash = "927a9d030a9bad114c17a4195f25a76f2ba9d0bdaf8e701f323e267dd1ce9edf"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "3ef96a88003584f3bb0e249aeb102b977400fab8718201f3325dd6ced30e4315"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "27941819f40eaaae282534788ffc1250fd414ad8a9213b26a021c4b19f3872e5"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "7876655e9f26cbdbed200681efc0854f6e0cb938a5187408d34e430892e4e670"
metafile = true

[[files]]
file = "mods/chest-tracker.pw.toml"
hash = "bbe9f0d7480927cfdb9e2f4d125367ef81f37c263ad6fdcac754380e3af7da62"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "d226ea199a740bff4e07877a952dc6972273fb92fcddd258a8989bfbede63a8d"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "d2e1ad62031e3700de73a87957a4acca747436a4135da695705cb5d293aa0890"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "8a8c8a5597d0f40a2b0ae97d3e34538bcc83ebbd6a3af55bc5f9151ae93f2834"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "3a74181901680e86eb8b66383f5b1428e205dc36f5b3a2ba230a81b3c1b808d6"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "32f2a6bc932eacf4021a13b9e48cf241cc599a8fe6b2add07404a2394a8da35f"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "2cc0459572ee80e4b4a95d7927e25b79fb8070d14c4a93e49ae30ff2a6e3252a"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "276e1986d17845723e3ff29ba3fab5ca02b3647b1ae85de612408d3aa621e997"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "ba0948090ee94a52b1a8871e1a6ae5259a866e89c75663b8dc442bd3f1dac393"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "5d9ebe88bd5f88c680d773a765f7d4e63f3b5a1fce2e23c4d04fc52d19cccc04"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "ce0b6c452313b669ce95d6bc7f232f72b89bf61ebb2013cac5b17a09c8132510"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "f2a92ab561a25a08c2a136f456433ab1fe2b67cc99c9265c3a6189daefd692db"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "c9102ad224c1496927d326707ee2cd2a2cfd6f278f05e23a19aa45395306daf6"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "a30e4e03362d1f636a4b8ba2fcee37362d014b04287fd48fb3d74dad4df9aaa3"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "34103fb3bcf4246f919fa0abce56b54711634e4a8624de2ee16aea1127bb4a3d"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "79daeea3b8e8747c00c47ba450f638f467dd1c7196f16be4c27e87ab6dd17c68"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "fff1e00559f13c092b17fa83804279cf70191d7a99a4a98a4eb6bb30ac9a78db"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "abeee28b9455ce8e1d037fdf573681968386bb7443cb7e3ea8e3980cb3c8b0ae"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "858b7118ce19537e0833360fbb636ff070639799a0d14b471e05aa834a8673c7"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "0f88e46eb7b6487e139e4cf9e75c3b6c2764ffea3a222655798a893399bdfa1a"
metafile = true

[[files]]
file = "mods/highlight.pw.toml"
hash = "58ace6ddc01192bd96668e2a833568083f34b0808645e056c0f1e0716f63abe5"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "060c6baaec85f47ba4bc2c0f4b8642b9933c27d3c166eb00ef86b4bbfd7f34a3"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "cc5ce2c69f275f245fccbb9f673f5b6711175034bdf41f48cfb672e652ea984b"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "62a5e15ac115d87e69788ee67f58adc82bd09c8edb7e32d78ec421280d887fd3"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "3154ee632b385645dd0f475997c1fd7ce30c670ae14e422cb9c8e2b0c5d67cab"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "fbf8ed68da06af1014e46752b0a925c01b87dcd2c7c98d3c110d907ab7900220"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "373b4e2259a18e43111d96021e8f1c1c23a7f9452890843851c6542211af3c65"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "9063bac3fdf585a43d318e3f9773475a28ecb8fe80bc7689cc480851eef97420"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8508e46b7e272d79dc6b3cc0149f9fd132c701369bcb2abb5c35da3ed92b27fb"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "694c91d6f341271b0b071a814fb64defbd52af1b228cb593595836c0d9f68151"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "cc298019c2d3a47a97e72363b942fe408e5ecb7ff476fe08155793f2f1578317"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7d348350c324d16d37c4208e38d13386a589fa2372cda9a253d3b5a3f9dda137"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "3d09d4abc3486966901f6f59935ad89cff4014dc221e0f56f693f85ef8ee58b0"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "f531a8ee70e9d78ee62a84e3fd18088070dcf8f2cee2384a8aabed16dbfafe6c"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "83454f7ce4c27a04aaaea45ac85d320551836efa574e7d7a83d1de1206e05313"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "60b7142931053dccea771de4eb969b6015a05b42e1f2f345f1f131508a58659a"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "fc423581b5fb0f2244930e5590b6863218d5fdc2c3c2a930b920a0080f77237f"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "e7287d0a0266a50af1bc4b283706578483c7aa757d4fbe37f39dc714bd139d9d"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "10430695ad67fd14a9e208c0ebe6efaf073cc78e3292f52159b2d04b75b87214"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9ce6efc7149cdae2deb751b4ebf2d220700cc1b204e7a1d026275203387f106b"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "a195edea1d57c1121bddb71d1ef1b7be9efcfc37e33d473ae82cbeb335de5392"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "b00b092d8b7f7866e1450398ad0c503db06b367855a88b4a620399572972cae1"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "df4c4fe3aff1792aa7d19d097d5d1bc0c6e958e6e4ee32dbf148ecac62e1274d"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "d68efcc17365557a070fbfe07c1523c041f3c9c41eb637beace220d2c13c849c"
metafile = true

[[files]]
file = "mods/particular.pw.toml"
hash = "63a2011c75cdaf07c0a537c1f5c0661b7e5e0471c81625273634f88fed05b9c4"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "a9769ced0531122518321833966d375196753db1c3a47b975aed4bb6837fae7a"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6c7980710f06ba63bcd36a2cdda88b34949f7c73975fe19ae4930dd30aee1e71"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "8b1f5a4ddb33a561b5f7c8067c90da759bee5919e99275587a5d1799fe461064"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "9cc9633e5617b3b83f2aaa0d2206948e5d69d0dc7ae500406a317be958ac65c3"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "bba144fd6fa19ff7c35a2a47bc3c023d11210dea2e5a4e08fba62617e7d0d01c"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "f29ba19cab72bdca9cbf01a557f5fb78513412094d4d4051295ab34ff1a86d9d"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "956696404fd9af1caa268648e4f5e6bb1133e2d712856851529e351316a013ab"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "1325400f1c9d2291ed301e426c9698d04fe6e7411eb062f425df50ce9f6ee2ac"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "d1597b194a050d02c04f7adbae5cf4a7baccaa3852c41e23268a8e124e061dd0"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0518255b54fcbb41f5ab3ee78fea75114c7a5bcb4bac4ec17e723b46fa6ce89e"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "04d19c3bd191f165a079769a6ef729e798dd1a2f68dfcc218019d2577daa3231"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "e53888490a33ad3127b09dd98ce001e579cb6c205a99a1e6e0424ab9f5b862c2"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "caa507edc23c21df56cda8b40d30d74eaa999b19bf2fe4e2b53cf9a256e1ac76"
metafile = true

[[files]]
file = "mods/sushi-bar.pw.toml"
hash = "6bfb09a5bf731cd8d347b8e77b0379c254b2e2dd2763c8051b6bfe122a22b7fb"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "ee103bf45111c2cd7ea2d9b31087867dd4b0d07a4b7dad7b138a4ae506127b37"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "a6482b6d67536a3e1e91015adaf9d99e686a88c87acd046ce5dee9e883e0fdfa"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "407b6a954f9c3aee145dfa649eaa0b336a6b31d7660476c81cba1da1f6ff54e3"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "fd725a2383164ee2866a41635b0a8baf4cc1506d33df1ce1cc1455ab98a32e01"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "7598f0435251f845fdf85c8ed2ac612b2d0404e0ee73a1fcdebaf4eb6c95296d"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6577ca23e4aa5d044d78199bd18d5664c2463dfbe2fdb5c083bf7f6cf7ccd002"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d2d5a9c835661b4f6f718fd057f03594b87aa49d1bcd9711af8553e51ea4a6fb"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "9ccdca7ead50871101f8cf380df89a160261859c7e640c3477170f95f1a515c3"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "c787950c5bdbff78bc2ef218554f1486fc81f747d7abd4a29fba5286229b225a"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "b843c282f94af79a4970c91879eff4073932409aa045b722b48054bd4b2fd45d"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "98520d370f14406836b850e9ca58debe0b5e25475279d7f2a46b1c3151b222a8"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "1bf292a425e8cd502411b21aac3d9189078ce76329ed5752e13653bb3e3bab34"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
