hash-format = "sha256"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "91c6a314e85ace68b65798fab355dddc222527ce2a2cb91613312f6c510dc395"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "0a87c2d4a488b9210aa0026d8db5ea488278f6492651b8dd691ffc70fdd4d9c6"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "c375509df57d1f34316b22e90ea0d233dc744d4e453b938d592d835e1463d8e4"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "a174ebfb74b63cefdca6109147ecd37d330174e44a64364cf9e1ab07778062c0"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "fe92368ac0942a8dd56ab8c6c02eff03a3ba0d8d4a5d74b899509a7d962dbb6a"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "5aca93ae200ad06af09e786a1eb8e3b2efede4a284782cf8ca1da0ecff2badca"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "ed1df535cb863c20c5b5961ea4c8bf07bdc3d5590957aed023bf9c0a671fa65d"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "1a53593054723f1f7096da9ef8cff1564c7fef4a1940eb4174e7f8d9ab5bcbd0"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "44d1193a481e30a110f7c44e0c9bfdb8083eda5097bec5474163bdc52b23eba4"
metafile = true

[[files]]
file = "mods/carpet-fixes.pw.toml"
hash = "5b48a918620ddca185e620307ab18a95d569cbdf85f303b4fe825121f898ce7a"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "a42e1cb16e5fafa1355a83ace377a92c36444c99ce627790fe2840176abe2312"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "0dfb97d394e0461ee27d29751c1551924ade6b877337ece2d28a4e1bc49b7fde"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "dbb14bf523fa5c96cf55135fa1427e6723f8587e6b65afba7f6394f1bdc74cc9"
metafile = true

[[files]]
file = "mods/chest-tracker.pw.toml"
hash = "0582f0522c41e2401fa8f9d320d70ae6871d90836a7eee78841d548894aa0dd4"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "f6ebc2055e809ba8ebf2f4c2ce0127effb2bbc6ff684909d352aed66e1f4eea0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "379c3cfb0a775914a1a66917f710cbfa3baa3e62cade49b5ce9bef55d158a4a6"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "67999d3a98be8ad98ed9386ad77724cb4083192e6ca7b4912dbab95a0b838627"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "8e057387e3d5de45d3c75668cb1508fd4e15b92c376da9bdfe7330f808c4c742"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "51fdb49c06039b92e65c384e95eeba0cc3f3b699cb120280558121ecacc2d494"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "c0c81018b8d604f404923eaaf8093c01ccb89fa7d0e46898fc94536414b7599d"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "6762e382538a59a298b9c5041638d9d70b06f854af2fb3500cf703669f487b66"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "5abf46e3e43a817e69c63b41c8a0dc9b89e5e16b70956c6d84eddaed391aa875"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "dff7ac0c8fc0398c3d5beebe80fc5fb56e4267cbda801045ee4bf49306d7d2d3"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "bea1d0d108d827902569b107767d8afd055909fcbbf587d31ff33888bae7dff1"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "20dc586c928d66360a26e6cf9fa4e61b5110410ed43afa25bfdcf4e3f611c061"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "0eb80e5eab074d997b644663fe4aa11516fc274722d188b843308da8f6474701"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "30bc2623a4fcf15cc6755279f7e3ca83f604df909d1afd2eb0f113b1a29c6874"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "ec6d0bc25af0056fc407f8378a514d3c037561333b51699569e857d71bb24855"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "6b8bdb0032798b056e4850fc662382a58fcec305006db995596306f70fc5f145"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "2492dd88a4427e6c3cd299a8817ccbe7499c0ebc60734de11e73b29042151f0c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "07f15bd07ec3c70f2196cb30c0cdcba681eb7afdc6489d0530826593d0dafb87"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "004d2776a51d79048bb39ea1d891ddc760de696a02de6bb9ac19c203165253a3"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "3d82d582cfd664f82a8c70c57007855dd7fc2416e4f3113d7211722501ed4a0a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "bdc937c2e64183c9893325e23188192c1197bb57eba15949161e56df0a9ae124"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "a454c13eeb18f9f983c3e1286639f1dd0539d142e72d5f6b56280c5947ae9e7d"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "1cadb07ed3568ce2abcf93e6bddd9384ff3db828f6800aaa3e7c7b81cb3f6e0f"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c190ec4b8386df056c909697113227e4a75923121405829b94b734f233c12243"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "88aa3ee84c4bbc34cfc50bc3a7a0bdb1a752459c78acb01c93352efd6dee6660"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "42b56fc173e615ca156ab89f3d196f78b494a1de9a1825910c4a4a7c42b7dab9"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "f5c3dc10dccf7aebcf65c0aa7c8ce367f7b1dd7130c7fbc7ba074d72b71e0557"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "d609573e65a0c0417060648951d396133b295f172fa8f21ce6566d66d27e8320"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "c768020ae2e21660ec0ba1fd6f490763527b60dd3a5eeb673934549e59a39e99"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "bed5bd5454ca8cc982a0f44e79b36a78e47f5620a41c1cc82712a2f075380437"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "420d672b98615c6e76b08796c38835a9d23527324f71e9d27e72bb2bfe29fb86"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "809e6c0e0db1bed5c31416f55826d30efd48a2e41a3c6a17b3faab3b71c503b3"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "70447f1f9cdb89e4deb31e1049bce488359089b1e90220380de36e80db1e77e4"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "0b754d32d37c6bcbb5a97b50eaefc296aa1fbf1735d9af4a7fd671def32cb9c3"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "b974082e807143052e0df98ad18dacc3c173d034e3a1c66c63e3d750246ef2f1"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "7edc8193787bbbea306191ab005d6a9c40c3a44b89a93142ab8d6cd21fc51274"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "d99d85da5e60df5e8a0ca1d630da146b858be34206d39cdd00c30053c4e08f5e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "5cf337b85313248799711185282d734c1e525dab914e2ba6edb2d4ea020b906e"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "df60e11c24d37f579ce2f3925a91c4c94d191099495d9f5bdc3c8fce0ac93a5a"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "ae90e53681efd54b374f76c267b23865a34a7a08e9343b784403e36140617795"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "3697b98974ed9d6f0f8f86734d80d612bfca512bcfc93be8b4a43c8f2fa3c918"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "4df3e94741133b7559aa1138c104d0b1ca7228cbf14397ae23dcd56416bdaafc"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "e200018576fb20575e17b60fa09857658e62f0d60d45bca850b1f50463a7421d"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "7f09a6441559ee709800a99efcc3507fdac95c248f55a2eb7ee8f5c7de6ffbe5"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "a8e9ea91385bfed963e33cb1224d69a1ad1393b7a293bd278e768ce780339810"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "d9c4386c90b8e0ad024378ae41b61d7f4f3590b058e651124567fb028b9730db"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "13771b3f0de6f1cca4d2a010ba770d86b2d647df5c56c2281bb7ea356d7e912b"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "61bea16186d7dfaae13969dfd311c9f36879aee6aabc93f7769449b056fdd0db"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "73e80955daed05d210161fdfdcb665523466c79aa2596f28ee9e31c39a3732e7"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "f1e72a7b4771a6e8a77a072ac525d348e8d72a33b1aac942574ec4ead0812328"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "747f9a6d4103f246be7745ff18413e8705732c8d6c64dfd52cf1616a1dc873cc"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "c6e4a9c612e7dd473f07132f041c14ce0ef5c7800308f11f703a48fb9c15664b"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0c83c344046d0b96fd7dcd9e5c98c44caa3d307126d502f202dba50855304fb9"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "3d8d51acdd46e5cd60b76feced0e7a4fff823324cdc72e56a16f6e725c9861e1"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "a991f3c5c1001e4eb4d2d576167f4818fa5d35458960f4f899a215c187a40d46"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "e030656570132a7e3b09d63b52a4479de910e05c787a3d8309d2bde493ffb3f7"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "004681f0d4d305dcdcda41710bbedbf938ec10c57b2b5a69e48ec2d7f772cbc0"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "7b2a08a20d4f18e68681ceb4a315a167e19a8ac0c073bfef6dc2f3ca4e1a07ca"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "1742afc46edb51d7122ef057bc85ba961228c41f6156d6d6e0ad6dac1f17cfb0"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "5c39ccaf246f622dea0265a35bddabed4e0757aa11563c5b13ee59acf35fec7a"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "05e86d99634d5b81b409aab7dd95495c86179bad91311013e2a10e74239b5753"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "2e6fd01696c404b4f0e013a4e62e661a0767e37b90d3630540d52ee151836012"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "1bfa78ec5d898176438a8e83bf100e58848d6edbe7bf883487f4ff339b35d64c"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "d9088bec9c98e2835fd39303447cab1202c4ce66fa24b833a5e43199aacda346"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "1bf292a425e8cd502411b21aac3d9189078ce76329ed5752e13653bb3e3bab34"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
