hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "bc0b2d242970a527d672fa2e09fb98828bf84dff97bc30d2614d74189ed49c9a"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "2934bfd58cac080e0f54130a8351f454c33d664e432253ff070abbfb091a3e66"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "8c74c1387d413eb57b880859a5c160ae751b23dc0d75cee1bf6b287ff267cf37"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "e27416a4b5e427e5d23f6c5a0c2418a3e88c85a456208079acbd4c4171e4378b"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "201814b124dccbec493f99385c62261425803460818f4565bd1b9276f1a8f516"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "15762ababc97f537a7a5974468ae68329758366f66b4d8ad8ed0ecfc1b63e95d"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "3d087b596729b07a3cf1c2f6ed132530d09ea478e7d8faab54125e8a6209d782"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "abc387a020c7ed360eae2841609ad0a69f0df06c668fbb27776e232bbc1c30d9"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "41a086c32768cd53b590f4a2f0c4232e02ea2ed2b2cfdd341a4ace3cd4317b02"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "177b482b2fa380214799c4edd086d2b9155ac076a62497ed6d38bf722b0fd708"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "a31670b6cfffabfe5668aad109263d63ffe5c1b8cd5cc65023b9383c03a53fec"
metafile = true

[[files]]
file = "mods/chest-tracker.pw.toml"
hash = "3b4f49741d6db4e34c68c18c830bf37aa3de6c7be72ac96699062bfa5e43d5b8"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "746f70bb8de0233b9775ff2092e7294854937f724122f54ec09a5a7005e716bc"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1d3d810fb49f6b74078abfb8aa2816715cc2840ba6324c9fcabff984b9b72412"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "8005d305298d1281e9bacfeea620046e6b8f0954114740b206797bfa6c9cc122"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "cd4d0c2db8c45235322fb097de824765c2e9ef1a762f8870b08680b92b8cede0"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "d333bb64278ecf214530c557529be70e095235a8f40244df0c3c4dfd6cdb45d6"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "518180314697dadfd8a159a53fd9ab37d8cf54092086e913eae45f5fd7603af4"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "f1374e6ee5f7cd2ffea8cb40ecb90a1da10c9d104abd181f152c95796b02d2f8"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "3c2a1648640346767eb9d0ff42b890ac922af4d71162cd30919e5568fe33be5d"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "cd6cfeb9762812de74c83498f6385d9acbf9da220fcb368ee30d1de634fcf215"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "9eadb937c438421e85a21338153114f97c75ab3dd6f3a49305bc8d0d7b3688aa"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "74b45be8e04ac0b8ab38d6bf5d57736596ec78850b2153963ae65b1944d5d5f7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "ae752165ef0ee8d816353e7c50f7772b996dd99c8bb271eeec67da0f2e001f7a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "e4ea82c32d3a00459808dc441a839e1f5ea9ba4f14917be596749bef080546b0"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "d88352f607700aed0db6a0679d4a2a2eaba2a83d38696ca966c2dace0a32f2b7"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "d213dc35ec09b56dcf792c1ecc557c81ecd9fb099d19412bef25c2e4974af2d7"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "dd060d54245bba4e8547daa2ea67d1180fa3d0194dc2528fc141b23a365c32a9"
metafile = true

[[files]]
file = "mods/highlight.pw.toml"
hash = "d38e21294196a7485a8c1ee3b123362036e69bc6903efbcd261932ebe7d385ee"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c3d4f2627461782145554911f6f5e79d91d25cb1cdfc2c7386769cf3b9c7b97f"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "866ad8b48e3ca159548beaaad408082116a6f74c9e36b8b9637adb068ae3a86e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "aedaac031578bcfcf9cd635d88b778304e11f893864e4cbfbddb67a8c8e34c14"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "cd9b2f623c12440b8e29bbb6f3458b2a6cea5cc2fce74edcad3c2ddeed11447b"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c7a27ddefc1a4b55d4e447902bbf6f43f797a69047dfc00278e16b1ff3e191c7"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "694c91d6f341271b0b071a814fb64defbd52af1b228cb593595836c0d9f68151"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3d2c6a7a3c6bf7e0dfb6f9b7a0d18eb714e4b236e9f88e80c06e38cc94655733"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "06bad9060a906d5af6e9e35dd551b882bf80a88a91515c89fc1c068b6971be01"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "f531a8ee70e9d78ee62a84e3fd18088070dcf8f2cee2384a8aabed16dbfafe6c"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "101ebcfba78e83448379c1388f7030bd5ee18de45219e0654425c53962a0a824"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "ecac2fb329b1f9bf5140bcb0f70d9ccb133051e6783be27dd9a117d1cb0f6222"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "37d233dbdd7469d0235e1fe8ea8bb37a180600a9ed338341ceb87a7850085633"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "285850d719877c04bf4b2e6171fd721bfbdcc6e3d8a37dd1ab591829aa7fe4d3"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "38ab12bf19d6cafd9208c4715a84cbfc1606af625f9fce9e253fed8251eaf506"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "06d0708b2f778731f7520021f2f3c2284a347fd6679f0227e97fea4140b374a8"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "c43b5e00bec64c5b0e55497ff758ffea9ee706d0246c22ad859aee22ec01cada"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "7109df72174bc3fe15d9f5435767d63c69cb03b49910095618bd80888af08240"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "b18d11b760aac0bdf2790d94faafa9307a687afbcb98d92b6080ac5539196633"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "f0baa8708ef16855f5bb5ad67578e67a003201331702d54bd4d84b25fb529a61"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "fbdf5f9010d5f83277f4cdd30d33ced05fa1f7db2b3dad9cdaf114ee99f7d8db"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "153de543c638f8766ec42562f9ac98f22dc6e8138d0f70c17260f3dde9797d4c"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "5328eb3fc883e125f3f2d4a59690fbc02b4d07649d9fae2c9b589ea190965cb2"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "d1b138e235ebc23ed621e2cd81bad86d2263c1ad6e67786debaef11fabd21259"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "5a956b5990049b620108bbebb064e557bb4a48f8326a54afbff0c04ed5fb80a0"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "7e759d858106e90d56a6588769de2318af283ad07c6260c6ed2a0626fe34579d"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "b61ab82e0128ac072934bc4f10a76d134e3f01c8ee1f41f5e8f1b7c1a2b59f1a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "4eaff00402d863a5fd6022460afbbf81e28e3d1a0b0ba9ab45854b12570f326c"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "c944e4e8d39877dd48c48a5fdb547218e6adc9287d33c88e25ea3226ea71b8ec"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "a8f167e99fd0c8f80d7d0a383de4220a0c5fe9fac10b72a2300f7882f597dc51"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "a6f20b121142bc29beaa55d1c44a1e02f117a1a11704dd54bc49bcf96f377ae6"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "ee103bf45111c2cd7ea2d9b31087867dd4b0d07a4b7dad7b138a4ae506127b37"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "dc67a6b542afb8c9d927c3e1717e313964f03329f4081c65ea93525d44bac76e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "617e8f9f38b5c6938f9fa4c93574679ab2ae229389b0750f31ee251469434792"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "017ca02510e461c1bc8dea6c80626ca6b378aa4939749c77954884383c9bef3f"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "35e6474329bca40af9199e35d037a8accfa5ec0c6779ab06f912bd1f7a2bff0d"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "48a6c4ebdc22d4ed7a3168d578adffb0ce25cf1130327bcbbe050384460eb76a"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "19e48b773677cc0d4a448e7ec5f4d82d7c9bd21063aac3c1bf710b4a78865c53"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "c787950c5bdbff78bc2ef218554f1486fc81f747d7abd4a29fba5286229b225a"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "b843c282f94af79a4970c91879eff4073932409aa045b722b48054bd4b2fd45d"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "1bf292a425e8cd502411b21aac3d9189078ce76329ed5752e13653bb3e3bab34"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
