hash-format = "sha256"

[[files]]
file = "mods/almanac.pw.toml"
hash = "ffe1f53da01d0c52d11c65fc137f2712b251a4bc68df86e415aec2df1e54411e"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "ed903d0b2e147daecbe0ab26174685d0179cd587fcf533e55aa30886eda480b0"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "352fe01e3b8136cf2abf742ddc8e2cab45fd7f25f635df960053b8290e5dc2a4"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a463f60553d19dc6cdb468e8a0f9faa73fd6694f8eb87fe11532c81e9c908dcf"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "284a7ccf2dc6ff43378230c252323359634f2b566212924ad0f138f4203079c6"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "385f6606afc7086a39eaceec2df95e0c2c5d7aa3a3b31cb67e2a337eb10a4167"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "74c01cc05241bb689fbb6bb7a26aebb4897b272fdbbf33f57c04fc453bfa75eb"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "dc1578a021bb4e5699524f5216d8aa9b08c9d30bfbfe0bc72bf07f5391c3f3b5"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "c62ded87bfe165a691ab2845149b09788d9a0cb308e44ee7ee6507c846e9bdb3"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "39d2695bf316d7d48d21da0ae6b38ea3e74c47c3b07c93bbade4dd753df90321"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "7a19ebcd18bfdf9dad3aa78e6d0e4931d6172029ef939cfeaf450660bda0e863"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "20d7b9a3333ef86d70c3b3becaeccc9ef5961c41e8cd936bb1df9cf0b946c546"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "6c725e481975797aafda2b25d3767fd242c6ea264d70af4617ba7e10f53aa987"
metafile = true

[[files]]
file = "mods/cave-dust.pw.toml"
hash = "a3ec5f966eef5e3e7d5311327f630dc4f387ab8d4313756b90147e83ee8a061f"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "691bec484dbe013d0f68266fc66e28b23fb3c9d80fd46665a85512130f2c562a"
metafile = true

[[files]]
file = "mods/chest-search-bar.pw.toml"
hash = "42362d607b1d9a7c8b65f78f33f6ca3a323e65a368187b53f9a2610d8aa82e0c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "13ae813426f52226d8363499d722df0933e84534f216eef127c198c18bcdbb6b"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "45f268d205841b54991ff5a25e126f2ab314ff814f6f0ddeb26ac41ead4a7a09"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "278a349024e41e039f9f4a278532b56d1774cd2f7fde04f2cff298f3e085d995"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "4ed5776aa285faad3d73e7df5ef2a35129c632ed72b167279ede5ddd488fcb4a"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "57f102e8b398add66e7580de4a7f6ad1cf3d3f8722494d7ae14145aa217f33e4"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "847dce2251028733f139692907e89466896dc6ca35cfcc1bdaa0ec1f02aebefb"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "1f1aa00fe099552dc0b9baa2542fbbf66e3d8f56c18b7f0d5c328bfc01f1680f"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "4e230e35117c08a4f63428b6b1d62b1e6d14542ccf91396dc4fbc98527c51db4"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "5b68880f4f5606aa7848d5b1ed9fbb7351a41094a3e5d1090d943b85a5d8bc0a"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "9a386c47e3ee11b91e443d8ec1b6084eb0266b5ddbd127ea3e90c7fa4ff5d9fd"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "2f8519826d90f9a4f30ebd70fe179c87771c40d5f331046dd43806219bbe255a"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "3c0c6acc3d164ee2b5bac79c0bd0996748cafca7872238fb16c8cc1bb8829acd"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "ddce8551ca0d76b79c3802afa2138b947992ab0fa1d4adec4e9a63bbd00190dd"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "12fe61275734cf8d2554d5f92af20ccb22479118b36a9a56a275ad3f4b1e13fb"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "646a03dd78fcad34dd93fbbdc09d64010dc0f04fcec42927f229ecf448cf1832"
metafile = true

[[files]]
file = "mods/female-gender.pw.toml"
hash = "4212a017915ae76fef59cc06b7bd68f0718c8439f04a8fccd77f7a53635de5a9"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "af10334d5cb965e4255f864d8fe2c3bad90e571492bf61fd84fb55c9a9506d59"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "7517e92e49506f8dfd06f6005505c5149b5ea7d423a0236bf390771f2c5aec7f"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "d6c762a1ae9e43903416e37af42f63f1c485051b77d44c5501a2097c1149b630"
metafile = true

[[files]]
file = "mods/highlight.pw.toml"
hash = "5310ba63bbcf2f482337b63f9a76154904935653a47279850e556c3120f35339"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "aff7a565699323a9319eb3791adfa5c24e230c92d947bc97714e816acb101f8a"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "5c9e35e1c2df866f97371ce64eb8d5428310716c7246bb77e542fcf62680d92a"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "fe4579562bf41feeecce518a5daa834dbe3af5f4dbe4ba3faf93a3f69a6992da"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "623f91f5cb2cfe0e7c3a6fc48ae5984dfad62e85389e2567ab5421f7d9d02c51"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "ced9729e413bbe2bd78889cbd3d3e93ae56b06c9728972a06ff03afe8a0f4eba"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "b84325343c5cd6c714a820b07b350414aa017e39fc3403b4962d87ef1911dfed"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "e26dacab5ed497b7bf6500e389eba5e21cd4b9d7b38089045cd26818a4d2f589"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "815ea1440c911a267d0264b74094d7ef471ddd56d2701ab77f3bb1666158f513"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "2038b1cdf8f16003e475637fd4913d3e68453a6104e907d545a29b85bd6c054f"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "d757a19408f3e9b09d4a1511f71ab912a2d453f9fa7f7e342067d298ff4d2cf0"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "29bc0f585963a84e1f78af8a1ab779e34dcc4c1657190297bca9cd95aeb90d36"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "ebc0a6c9f39a73686aea16c4ea2a82fee370de3a6ed901a4348c05af40c3a5bd"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "1d19237dc3a66d87a018bafb3f69e701bcba8ba1fdef71d9a5f17222c15a3120"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "7e57affb55a7d3a5cfe9db4ca5308835f410644f8e500b6a13a8e04b3e340515"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "e945646366d2097d79ab4db15ed47c0cc184261a588456573954b8cc85eee518"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "14800fc12fd4b92497c0f26455523783bdf59194233bdaa71d4864b3d436929a"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e48fadea92533a14b45d8fb64ed10e5942ee90bba874589822a766a6d47930b2"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "8d250e4781a41beb98270b2f36e042415067f92081c6fcf843d7ea89a61b4cdc"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "4aef3c4dbc01c945f4a30f63c03607aad77d16ab194983510c10ce516312e258"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "c71075106b0f5ddc29718d90e923c62388e4b17d741ff34a3cfa1cddaa43b86e"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "e94c47d7679c5a6a4a3deccaa7bba8f7c3961a70f6c03c32adc809d7135c87cc"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "438f668eed636071ebe6ab8445d9ef37af608467c7fcdd243676b24be50360a0"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "d85ebee3dd81e09a850b814c294d0686ce4030b4ec0c319b1445981c98dbd376"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "3c79199e4f8a8221ae7095f45a83655fa3baebb59e4cab3d2544be52d1b29df6"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "0f40f193cb8243ba7236e227734628635399b4d719ffb7c27b93cceff4254149"
metafile = true

[[files]]
file = "mods/particular-reforged.pw.toml"
hash = "6a7d9d01de427ce5c40a673932bf99f90518712794d48f92f00d59f44d0cbab8"
metafile = true

[[files]]
file = "mods/pistorder.pw.toml"
hash = "5f6ded92142680f06d5e6d1dced36916b967f39781cb425c36da406243a5a8d7"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "799419e64ed42a8175333c541a08995fc4d84a2c6000877f60262fe55892e3ff"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "670aaf37ebb497d2d2906adb33c46c086f6b544f365fe562196f40a3a2d9f27c"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "dca39362a2ec9d06649094a5bcc8d35b93e791b26589f3c4c504a5f46de16f3f"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "f1de93ef81913dabdd6a4848c5d9d868c41a0d3e8db3e78468b0c555ec139113"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "f04be730a6dde5e7e3ce302260bc1a456a4e0fd57a00755d3992f9c0daafd21d"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "fb5447218bd3d1bed8a30af8f6e16a581120d882ec5a7146edc835df41747e36"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "558c83082e8e3415e24d4579ba1028da55b92747ae347bee45f252fc255d3a8f"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "4bdb139f7f4329e080df6b9467c73391652dd85665a6a37dbce799f08baaa219"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c117f1abe6597e6c6da99a650072ff7d5d150d0f0d3267b4429f0d9b11c531dd"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "928c57d2ae2da7af43f24ce9eb88c871d9f3d9165ccbbad91c13d2285a3c467f"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "abe9878dcb237d56e2ba70c17db8c721c6c2b8e62b241bc333539d5bc6be938f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "700caca572649f238e804258f79d25969031be3e1b01d0384eb54a13200caba6"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "7c450da0da231a6e35c64fd98c395a9b7a8822ade4e42363db1b28710e0cc0d2"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "b125a0e974eda8189374e57a8b412dc5d35706d4b16c50fd9039734868924c31"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "8e009ac87710fbd8f5990285d36ab2b4755e932664ca1bcb9cdfac116d6e3b6d"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "42cea99da1e022945f3da24049679c4308d9a33fe782ba17627968f2b7ff85e8"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "2fcbe0a98ff51dc54a24d983251f478c29d4d6cbe731abb3e7e002263931a317"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "d1de6d3e889db21acd36afb754f20b6ccc8c850cb7ef839047eb440e6114d652"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "fd5727735795dd7c724da92e982b50653b1d75d8550154c9d053b9d58a49ee15"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "5020216689686f6c43deda262c941d74158fdd44b31a1b4c1e2d5fd710174686"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "0de903f6957cf16eca63c7eca70d879b6d7c97d73f581659b8cf3441eff765d2"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c9a5dca078d983e94d629ca4bf402fff78e364e5b5365ff43373d77eec268432"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "4d54a64972ea89e49f314867802406f7ca73fa738ff35320c938f980ac0c8f4b"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "3bd80b33acc0cd9392e98bdc0becad357e15895b91b4f15d3ae0c5fde613a500"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "b843c282f94af79a4970c91879eff4073932409aa045b722b48054bd4b2fd45d"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "387fc5bb6d1c183e58e6efc77742406394096d40f18c042f7a3209d608a50c4b"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "0511040326c7649fde9b5784fff73b083f55e4ae7d43bfebc5e494cde0fe49e3"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
