hash-format = "sha256"

[[files]]
file = "mods/almanac.pw.toml"
hash = "b4dd3b4217e0cf479207818b743a38f0566faa947e7b7d0b13c91e1a79d35e3c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "284a7ccf2dc6ff43378230c252323359634f2b566212924ad0f138f4203079c6"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "193d5e761da6e90a51d40f2a5827cb900ec7643f0aff7e6527578fba53f341ec"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "f1abbc18408577afdca37f201e5fcca3ec702ed39131d9cffab3a6e3747917d8"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "ff53dca96285b4d8ce49a4eb7dc4416deeb747928b00da0a856d43c448ffbff7"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "0f8a9c9c738ec1ee47d2b45813a922d0907d22865572e65526021c055b9a3f07"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "77c88fc2f3c4d3a17c329e83ac40ea091410fa1f0b5ba5d812beb8e9c30e26cb"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "8a8d6af7aa8cb063e2b8fe7b29cf20a5f8384e1fee0ed7bb1a4b32d6ff73e919"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "b1cd73231544d2e55928071c3685f6a3df0e8b72725ca6c10d9ee2b7c816b166"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "0af258e9a12a117ded71171f3dc34831cb980043e63d424342bb2c11f1201f6d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "4700fcc4fa1f3565cf3ef54dad8673bc940d83652b07dd2461c88b4a5b38aa16"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "a853237fa57891fd1d6f73c77da86b6dfcc119234a7c2ef29c5a0eea575e8d22"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "5b68880f4f5606aa7848d5b1ed9fbb7351a41094a3e5d1090d943b85a5d8bc0a"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "04851cf23a0fef9e213180bf5926b705c5ad2d0b04d41934b915cc1ccfabd841"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "3fa2fe8518693b1b847572ebc51b7ba005e9046e400fc8140ad095c1e79f1382"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "61d64eadda8079ccd7c906a3b5143ab5b9b3716918c775dad2d3d59dfbe7bb41"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "11d459db9a173a8327b06be0deaf033b5af6ee290d85a5efc415a9a29b43ed4e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "95f01e24b5619550ef8798d36b2d49f9b814d67f9b4af33535a9be02c762321c"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "9d9207b19fefa97d3e36e04b31ac1d49d7f7a251d240472e64fb5a608073553e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6c7ba44c3890c9081e7f27b6b9adb49d96825581e522869d455ed7d45a16aa3f"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f081dddf8283dd5ba0db0bac8f438f4ce645b9beda391e901f27bbf2f5890d25"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "9c294e3f45df315b89228381fcd2180451de915ca6dec8c87533ad6b80192b0e"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c4e45594c8d1ab3dacc3b49142f16fb253178dd31d97cc917bf4a4d54f21e081"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "e9cec7e5877b6e6f83c24bfd49cef0e4df5235511b2ed87f90c5916185a4e6c2"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "40f59ddf22675273fcaea973d83ca2cee08847a6aa1d19a3a499f8f86e3754b6"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "da82ef9cb9353b9ff2701172e56618a60a357bfee92d1c97a875a5d835a6cdc9"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "46e175b662617498d6f250e57f3f66b1b39a40252933b3466e1ff6a7f6209725"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "1d19237dc3a66d87a018bafb3f69e701bcba8ba1fdef71d9a5f17222c15a3120"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "7ded2108571bbaa0be4c438e6ef4c6af25409b18d659feb07c0f43dcaf52fa39"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "bac08a2ea56bcf0089c4e72aa3fc9d73fafd85539736ffd6670b34a3499524dd"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "8df15e4c82204449bc611392e13ba20e6586e9be5aedc65260deead2de0b00f6"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "3e5664fd8bb133649bf1627b4bedbc0becbd329de88aeed41bb02684f13461f3"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "c71075106b0f5ddc29718d90e923c62388e4b17d741ff34a3cfa1cddaa43b86e"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "477ee00ae9c0473f452c78a3191428a5758486c4e74955e0fc741481fc5dc14b"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "42e99ea03a01f933a334dfdfb6babbdcc5d9b38c076e4d3c821a96a9730318b7"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "ed507d3c343158351f2065f8f4690636c761d3f3fa60193063fc6e68d6c52d54"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "6b2abdc14fca0b9b42b5678e7c65af8b93d5032f0e4b0d2fbd93295903489d50"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "9e2d2f5635c8ab1cba1ee77a4b9d23a0173b01417613db0cc8dab60465522662"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "d0a563f51108b76da07ab7ebd9454784b7c337630a5bec1a8a95f6ac45f9c25c"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "a5e422bc78dd16582f55a3d584197759d52bb493c0c2da4dc5263a72a654715b"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "faf73f436a58c66ae9731ccc082596cd73954da0c3b60bf8e93033a760a80707"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "d8cd3fa8968764580b91660ac62f3a30639dd258563fb90f418b6b8157368e2b"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a18faac8593412b5ef8ee28bf49ebf7fcb16197aa4d2396dd0684b7defeb0b59"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "c7c6894d207ecc12adcce8cb6e4128543d0799c94e0245d935a3419ea0c29f36"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "85a51da7bb6491827eb92fa45bee39ba27e116813b7582f5163aeeb80b956c0a"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "8e009ac87710fbd8f5990285d36ab2b4755e932664ca1bcb9cdfac116d6e3b6d"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "6b96c7f276dcb54d0f9275e83bb366b3d5b104587ab2bab7c38f7e756672113e"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "146dbdc9a45f945693a356510b0ce7ef670ab1bbd73e7fe461cef41f33519c3c"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "2f6cf44d47b89ac8560433aab6509f973c07b88db45fafa8cbf55aa7bd916e69"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "4e4336072ec360e6ccff331a274695e188920aa50fa74cd1a98993a4562912a9"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "19e48b773677cc0d4a448e7ec5f4d82d7c9bd21063aac3c1bf710b4a78865c53"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "590d63ddd680c1a9ce96945cec48c1b1dca146090003c850cf7a9cb855452699"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "b843c282f94af79a4970c91879eff4073932409aa045b722b48054bd4b2fd45d"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "347564c7db8830d5595e0c6cc3b7c4bb9d040cfd09272d672a969200cb24d3d0"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "0511040326c7649fde9b5784fff73b083f55e4ae7d43bfebc5e494cde0fe49e3"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
