hash-format = "sha256"

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "6334807483214e21b0457dc485699a5b6ceadaa3d96500954d1b7704f874083e"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "1f1d9fb411af408ac6ae2406e0f50c69ce80a5957c2d0c063416e394fda7d3a2"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "c06bfaed1bb50e273d42e7238ba2e14684080d898028e2cd49d89b3272494c41"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "81f33c0b5ee9c16ef3bbf97e0f8caed6eb3add0555c41dae7ee926c734ae8c7d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "c203d45ab48ce4b7b5e19a2a4e7c3b3748d8dfcd4d09d97fb3ffe59892e44a14"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0a8352a0dfee7b46d1cdc17cde75d9353b3829a30f710c42f7afbd16c7020332"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "cf3b0e9ec8abf6a1ea83510831beaaae9f44bf1cc07774af83f5ee5e483389dd"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "7090a35c56713cfcb4aa6eb8eec59a528c3ac5931281f34c7c86e34acee9a999"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "29ab91e23d3b9045c0074fd3d15ae625ab054de8a911cd2f814a04fcc8b18f63"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "f513fd5f8480f5b765ad17c4dd61fd250987e004427170e97f194686e43e547f"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "6fedfda6e886db56206a7e6b08d48811edf6639055b39cb754acf67c5bc58be5"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "49e67d8a8cbae979b97071253955fe75b8cb3db789ca40a4140548790e2fd3a3"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "7b5f96554cd02083d5eff7400cf429b5164a95c405fc2db2aa2f27d48921f68e"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
