hash-format = "sha256"

[[files]]
file = "mods/almanac.pw.toml"
hash = "49a33ac37445e3c08eb1a958b4f81f0c9ce356a8c08ace17e5df98e18558b4b1"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "173191aadaf2d4af72abecb3f911bd78f66baf2be90695101fc9db680d863f91"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6187b9cadca608c7d1a00c9fe3a826a2dbfa20f089235147fc9bcfdd85f0c250"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "ff991657ef2511d8f02a9999d55ec367a37b20a3987eb1d75ff82ba720a96aa5"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "a8fe779847f0dbe2fd01e8e14d2c457f049f94b34de90b9d21d5453332945ab9"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "12c4cfdac7981abd1c17758c78f8cd3d115610e2c07b017b2e4a61a975aaaa76"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "38946f6abeed50fffa9d9ae3b03c1bdae9e687050f6ff845282cbf099b74bbe5"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "6ebb236b2a46dbf564aa2760a68027703e44105ab18e77ea76c0fe2323a9bafb"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "e02c60e3243dde712fcdc279f0ee21d31f530d58f11402c0fcb082bb429e339d"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "4a9910d74bb7a85600abaf36ae568bcfb10e76062b9d5d718656f5d172e79419"
metafile = true

[[files]]
file = "mods/chest-tracker-port.pw.toml"
hash = "1489dca89d8ff03d900ea6ced5346345f21af8fc9c2519c4ed217e298460c191"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "bfc821011dfc8b9bdf7f8ae55377fbc57d5867ddf164f268f40ad02b4d201565"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "d61eea65d903963fc412f1e6dc4ec5c9f89814358e324cb734e0ec6e40ece483"
metafile = true

[[files]]
file = "mods/cut-through.pw.toml"
hash = "6732550e98e234ece1c854c2f1fb97fe0f5209f42556aad44b1c5785c4c18925"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "63b74d8b42617f58c6e6fbf9ae4cffb414693c119c94e669aa137eccaa4a5a0c"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "4e230e35117c08a4f63428b6b1d62b1e6d14542ccf91396dc4fbc98527c51db4"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "5b68880f4f5606aa7848d5b1ed9fbb7351a41094a3e5d1090d943b85a5d8bc0a"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "63fe49aaee4880ff28e30aa558084f7322d5ec2bf110022bc5ae89a9be5cf2bf"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "4a9def539ee4c0b32e12e148d1565a07916ad13ce9e6911864bfdb67f905c9c1"
metafile = true

[[files]]
file = "mods/eiv.pw.toml"
hash = "b6a7d72694aa3393fd5804eeda668bc4a552325e390b121971a5e716850b67d6"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "4a7074c226aa7dd11a5a00cf26016566fe74fa155c717157f938de4d46eab97a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5443c56a46d7fca84a1f96dc58315951a24cf8954f059aa35f213f28214d468d"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "48a71da0cd96100ccc239fa88fb6280094f0a0b1a555a2bdcc2e58dc2d7ebcc5"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "0df5b608f6521692c1434583a92f944e303881dbad0fcd98a5b5d37d7c22367a"
metafile = true

[[files]]
file = "mods/female-gender.pw.toml"
hash = "2e65a1caec1a30a06c6677e24230b05375fe81a728e26dd5ab1221e23cefc37d"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "fceeee5b54a4cbdf5bddf6a7d12739d9bf3a1c59ee6608211b0c6fbde91b740f"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "9d12f51a932b25751b7595ca46439a30bee2c26bf6d9913ccc9a27ade1972f36"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "88164a8cb5574252a7acb82fe650c096b272f7912f00cd91c9d1dcc2a18549fa"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5a6ee9ae2de75743aa027eb753ac9c3cb92305df67bde8fe2cefdd2df0eb49d7"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "cf2220acf2150dd1bd105c354ce93eeac513fd358e05105826550d73a5425afc"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "f759ab182ded464342c31777352e65a28e5e492a270fb7c20dda71daff9873da"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a077e0482f50add9ef20e962a7939aa678583cb3f354fb6b6124219badafdd4d"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "bdca3c9a098de3c08f996b214cf10ece27351f5f7871c30ff826a2f404daba33"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "471c02eac5adf025ed2246c2d3efd8267c67574f1bc7329b49caa1ada17fbc9e"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "3ded8f0e2b2408286789398b6a82ed97e55dd0bdec5585937c293187f133c342"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "81ad929a9824037e5586e96c510d6f83d343365aade95e99456d110040ecba53"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7fc67cabd5de89ebe9d7d995cdf160ceff0572c2bef784e846675976a428c9fa"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "ffd2bde70110ba1d26bf841930556307a5bdfa3159b194e6e30ac5192be61754"
metafile = true

[[files]]
file = "mods/make_bubbles_pop.pw.toml"
hash = "113af68f0f6a6490c66b13bd0f2641ecacbb5320b930cc0bc5574dcc8f070474"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "dd9c014be7eed04ccdba9604602ee2618d1efc424e16807c9a95e319f9407d8f"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "e0ec01c5bc3591ba368bc2e91c930680fe0e60eec1f18ac3565f432eea01ee6b"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "204a4b3b041fad4bb4dc543c74d540fcf239710494d2130cebe700bf1d8a7805"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "dc24a4cc0ad484d6593997c197ea602fac4d98c45dab0de6421e704c3851acd9"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "c0b691fa58c8a7177fa08fe8577324f82bae5b120f80c21a1b38fa2fe55e7e84"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "70d7b2bca719eca2b3a1447228b868abdc633c38121652d49f4e34380c44339d"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "958d770c8024a7c901315c786f6060554b5583ae302068526766e42c31b5f604"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "11d24c43e240249b5dd24e0dcdb99b4c3ada768c1cd1664ed18fc498d6add67c"
metafile = true

[[files]]
file = "mods/particular-reforged.pw.toml"
hash = "23e94d5ffcfc5250d614b41e35bcb7c619888f3fa76845f3bc07e3797b45147d"
metafile = true

[[files]]
file = "mods/pistorder.pw.toml"
hash = "259287589950ec5af4f2f1332236eee6fa10471eef1d1e30985d1e7dd17a5696"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "44bcf4409632f3ba850b582fc2e91787177e821bb5118b6b0c1d069ea9362a53"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "019737abe9c9d7ef3638556e810babc2a3258a5c9be6cc15b79f780e71db7fa9"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "89837eaa44abe7bb598faf2012531f5a3335b1c413624c6eff44031e8ec48238"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "42a73228a2e7ddd0a2ebba1e2a03dec5dbf4605854ec89c05f7e1374baffeae5"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "8e0dd3e606968ee0aea0d95b42a472ea921d5f1e754eec4bef2fc005f2e7f663"
metafile = true

[[files]]
file = "mods/rsls.pw.toml"
hash = "17f1f78051aab0bb1b9855f9756ca41fe14aaefcedd8a3b772d8a9619d675794"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "bd7760e94351d6e7c19eb1f155c7a5a7fd281340b7bd556da2765e931f6c9ab5"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "85ebe0d8d1f0f6bd943c1a87f5df47869fde7ede4d9d0bc90a2aff13a760c5dc"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4f57108f9e1c6281cfdaf3812e6bc2a2f16609a845c9912218ada90b1603e1b3"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e8c961dbadf2dde334c857d0b42a6c6452aa77a146cf80d4febf7f46e4ac2ef6"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "ae52c6ae8a2f2e6ab55d9387e0fa25447f62866fed9acc5758acfb8b1907eabf"
metafile = true

[[files]]
file = "mods/sound.pw.toml"
hash = "9210da9646623ee52aaa1bd7b52de6b02bd94ab70079bab6fa73c60ca89456fe"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "8e009ac87710fbd8f5990285d36ab2b4755e932664ca1bcb9cdfac116d6e3b6d"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "c061a86d6e29e5a02f707c30fda4b87669c672e9a8fced1bc4da8b9ad9fe2c2e"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "52bb2ec179cbb605d0b3f3d71b363cea0717615e433706346cad68f0c3c33695"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "61d853a4f2d353ac126a8196414efc82d0ca0402da2a8e492383dd539bfe4976"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "993390d4661a77aa83c8416f75addfccaf7cee0a7a7311a21742b2036700b5ac"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "53c8bc02c9b10610c43fc29127039036217e33a95ab2ea2d6ac291987266ef89"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "cfa4ddfc8999e7be331c6dad1f2a0372f996243241d21697939e6838b3402c6d"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "22052f42b1b73226d9508ef42af962471c79c7daa281aac66a82a90c7d7bb9e5"
metafile = true

[[files]]
file = "resourcepacks/even-better-enchants.pw.toml"
hash = "4f3e46f03f3af082015953f22c6600fd20e464222a20655b6aa1009d6ba65cc2"
metafile = true

[[files]]
file = "resourcepacks/fancy-crops.pw.toml"
hash = "b843c282f94af79a4970c91879eff4073932409aa045b722b48054bd4b2fd45d"
metafile = true

[[files]]
file = "resourcepacks/low-on-fire.pw.toml"
hash = "a325c5cdc15dd6aa3be064b3b07b1b7e343858b62b268cd224843cfe6916db67"
metafile = true

[[files]]
file = "resourcepacks/new-glowing-ores.pw.toml"
hash = "0511040326c7649fde9b5784fff73b083f55e4ae7d43bfebc5e494cde0fe49e3"
metafile = true

[[files]]
file = "resourcepacks/small-shield-totem.pw.toml"
hash = "a355a61046b779bf05ac836149ebf9db7dafc43138024b82d5050a911baf97be"
metafile = true
